<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

/**
 * ══════════════════════════════════════════════════════════════════
 * Seeder ۱۰ محصول واقعی و کامل — فقط برای تست بصری لوکال
 * ──────────────────────────────────────────────────────────────────
 * هدف: پر کردن دیتابیس با ۱۰ محصول کامل (هر کدام در یکی از ۱۰ دسته‌ی
 * قدیمی PEOPLE/BUSINESS/EVENTS/FAMILY/KIDS/PETS/ENTERTAINMENT/PRODUCTS/
 * AVATARS/VIDEOS) با رسانه‌ی واقعی (عکس + ویدیو)، مدل‌های AI متفاوت،
 * قیمت‌گذاری، سئو و... تا صفحات Home / Explore / Trends طبق قوانین
 * واقعی خودشان با داده‌ی واقعی تست شوند.
 *
 * نکات مهم برای توسعه‌دهنده (یافته‌های کشف‌شده حین ساخت این Seeder):
 *
 * ۱. فیلدهای is_featured / is_new / is_trending / show_prompt_to_user /
 *    face_swap_enabled / multi_step_pipeline در $fillable مدل Product
 *    وجود ندارند؛ یعنی Product::create([...]) یا fill([...]) این فیلدها
 *    را بی‌صدا نادیده می‌گیرد (Mass Assignment Guard). به همین دلیل این
 *    Seeder آن‌ها را با انتساب مستقیم پراپرتی ($product->is_trending = ...)
 *    ست می‌کند — دقیقاً مثل چیزی که Admin\ProductController::store انجام
 *    می‌دهد. Seeder قدیمی ProductsSampleSeeder این مشکل را نداشت چون این
 *    مقادیر را بی‌صدا از دست می‌داد (همیشه is_featured=false, is_new=true,
 *    is_trending=false می‌ماند صرف‌نظر از مقدار ارسالی).
 *
 * ۲. HomeController ردیف‌های صفحه‌ی اصلی را با مقادیر قدیمی و ثابتِ
 *    category (مثل 'BUSINESS'، 'PEOPLE') و subcategory ('Fashion') فیلتر
 *    می‌کند؛ اما Admin\ProductController::store/update فیلد category را
 *    از نام فارسیِ دسته‌ی جدید (Category::name) می‌سازد، نه این مقادیر
 *    قدیمی. یعنی هر محصولی که همین امروز از پنل ادمین واقعی ساخته شود،
 *    هرگز در ردیف‌های «کسب‌وکار»، «پرتره» و «فشن» صفحه‌ی اصلی ظاهر
 *    نمی‌شود. برای این‌که محصولات این Seeder طبق قوانین فعلی HomeController
 *    واقعاً نمایش داده شوند، مقدار category/subcategory را عمداً با همان
 *    الگوی قدیمی ست کرده‌ایم (نه مثل رفتار واقعی پنل ادمین امروز).
 *
 * اجرا:
 *   php artisan db:seed --class=Database\\Seeders\\TenSampleProductsSeeder
 * ══════════════════════════════════════════════════════════════════
 */
class TenSampleProductsSeeder extends Seeder
{
    public function run(): void
    {
        $created = 0;

        foreach ($this->products() as $data) {
            if (Product::where('slug', $data['fillable']['slug'])->exists()) {
                continue;
            }

            $categoryIds = Category::whereIn('path', $data['category_paths'])->pluck('id')->all();
            $data['fillable']['category_id'] = $categoryIds[0] ?? null;

            $product = new Product();
            $product->fill($data['fillable']);

            // فیلدهایی که در $fillable مدل نیستند — انتساب مستقیم (نکته‌ی ۱ بالا)
            $product->is_featured = $data['flags']['is_featured'];
            $product->is_new = $data['flags']['is_new'];
            $product->is_trending = $data['flags']['is_trending'];
            $product->show_prompt_to_user = $data['flags']['show_prompt_to_user'] ?? false;
            $product->face_swap_enabled = $data['flags']['face_swap_enabled'] ?? false;
            $product->multi_step_pipeline = $data['flags']['multi_step_pipeline'] ?? false;

            $product->save();

            if (!empty($categoryIds)) {
                $product->categories()->sync($categoryIds);
            }

            $created++;
        }

        $this->command?->info("✔ {$created} محصول نمونه‌ی کامل (یا باقی‌مانده‌ی آن‌ها) با موفقیت درج شد.");
    }

    private function products(): array
    {
        return [

            // ── ۱) PEOPLE — پرتره فشن حرفه‌ای (Fashion Portrait) — همچنین subcategory=Fashion برای ردیف «فشن» هوم ──
            [
                'category_paths' => ['portrait/fashion'],
                'flags' => ['is_featured' => true, 'is_new' => false, 'is_trending' => true],
                'fillable' => [
                    'name_fa' => 'پرتره فشن حرفه‌ای هوش مصنوعی',
                    'name_en' => 'AI Professional Fashion Portrait',
                    'slug' => 'ai-fashion-portrait',
                    'description_fa' => 'از روی یک عکس ساده، یک پرتره فشن حرفه‌ای با نورپردازی استودیویی و ژست مدلینگ بساز؛ چهره‌ی شما دقیقاً حفظ می‌شود.',
                    'description_en' => 'Turn a simple photo into a professional fashion portrait with studio lighting and modeling poses while preserving your exact facial identity.',
                    'meta_title' => 'پرتره فشن حرفه‌ای با هوش مصنوعی | وطن AI',
                    'meta_description' => 'عکس خود را به یک پرتره فشن حرفه‌ای با کیفیت استودیویی تبدیل کنید — سریع، دقیق و با حفظ کامل چهره.',
                    'meta_keywords' => 'پرتره فشن, عکس مدلینگ, هوش مصنوعی, فشن پرتره',
                    'category' => 'PEOPLE',
                    'subcategory' => 'Fashion',
                    'status' => 'active',
                    'tags' => ['فشن', 'پرتره', 'مدلینگ', 'حرفه‌ای'],
                    'thumbnail' => 'products/thumbnails/ai-fashion-portrait.avif',
                    'cover' => 'products/thumbnails/ai-fashion-portrait.avif',
                    'sample_outputs' => ['products/thumbnails/sample-profile-ai.jpg', 'products/samples/ai-fashion-portrait-2.webp'],
                    'media_type' => 'photo',
                    'preview_video_url' => null,
                    'primary_model' => 'google/gemini-3.1-flash-image',
                    'fallback_models' => ['openai/gpt-image-1-mini', 'sourceful/riverflow-v2.5-fast'],
                    'prompt_template' => 'یک پرتره فشن حرفه‌ای با سبک {style} و پس‌زمینه {background} از تصویر مرجع کاربر بساز، نورپردازی استودیویی و ژست مدلینگ.',
                    'system_prompt' => 'You are a professional fashion photography AI. Always preserve exact facial identity from the reference image.',
                    'negative_prompt' => 'blurry, distorted face, extra limbs, low quality, watermark',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'style', 'label_fa' => 'سبک فشن', 'type' => 'select', 'required' => true, 'options' => ['خیابانی', 'ادیتوریال', 'گلمور', 'مینیمال']],
                        ['name' => 'background', 'label_fa' => 'پس‌زمینه', 'type' => 'select', 'required' => true, 'options' => ['استودیو', 'خیابان شهری', 'کافه', 'طبیعت']],
                    ],
                    'timeout' => 60,
                    'pipeline_type' => 'image_generation',
                    'subject_type' => 'face',
                    'identity_preservation' => true,
                    'identity_strength' => 85,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 1,
                    'max_reference_images' => 3,
                    'watermark_enabled' => false,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'per_credit',
                    'credit_cost' => 15,
                    'display_mode' => 'card',
                    'card_shape' => 'portrait',
                    'gallery_layout' => 'grid',
                    'card_label' => 'ترند',
                    'output_type' => 'image',
                    'output_format' => 'jpg',
                    'output_count' => 2,
                    'resolution' => '1024×1280',
                    'aspect_ratio' => '4:5',
                    'delivery_method' => 'instant',
                    'estimated_time' => 25,
                    'price_tier' => 'premium',
                    'discount_percentage' => 0,
                    'platform' => 'both',
                    'accent_color' => '#EC4899',
                    'explore_tiles' => ['1x1', '2x2', '1x2'],
                    'new_display_order' => 1,
                    'new_internal_code' => 'PPL-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => true,
                    'new_is_recommended' => true,
                    'new_is_beta' => false,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => null,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => null,
                ],
            ],

            // ── ۲) BUSINESS — پوستر تبلیغاتی ──
            [
                'category_paths' => ['business/promotional-product'],
                'flags' => ['is_featured' => true, 'is_new' => true, 'is_trending' => false],
                'fillable' => [
                    'name_fa' => 'ساخت پوستر تبلیغاتی کسب‌وکار',
                    'name_en' => 'AI Business Ad Poster Generator',
                    'slug' => 'ai-business-ad-poster',
                    'description_fa' => 'برای فروشگاه، رستوران یا هر کسب‌وکاری، یک پوستر تبلیغاتی حرفه‌ای با متن دقیق و خوانا در چند ثانیه بساز.',
                    'description_en' => 'Generate a professional, on-brand advertising poster with crisp, readable text for any business in seconds.',
                    'meta_title' => 'ساخت پوستر تبلیغاتی با هوش مصنوعی | وطن AI',
                    'meta_description' => 'پوستر تبلیغاتی حرفه‌ای برای کسب‌وکار خود بسازید — رندر متن دقیق، طراحی مدرن، آماده چاپ و انتشار.',
                    'meta_keywords' => 'پوستر تبلیغاتی, طراحی تبلیغات, هوش مصنوعی, برندینگ',
                    'category' => 'BUSINESS',
                    'subcategory' => 'Advertising',
                    'status' => 'active',
                    'tags' => ['تبلیغات', 'پوستر', 'کسب‌وکار', 'برندینگ'],
                    'thumbnail' => 'products/thumbnails/sample-poster-ai.jpg',
                    'cover' => 'products/thumbnails/sample-poster-ai.jpg',
                    'sample_outputs' => ['products/samples/ai-business-ad-poster-1.webp', 'products/samples/ai-business-ad-poster-2.jpg'],
                    'media_type' => 'photo',
                    'preview_video_url' => null,
                    'primary_model' => 'sourceful/riverflow-v2-pro',
                    'fallback_models' => ['google/gemini-3-pro-image'],
                    'prompt_template' => 'یک پوستر تبلیغاتی حرفه‌ای برای کسب‌وکار {business_name} با سبک {style} طراحی کن و متن «{offer_text}» را به‌صورت خوانا داخل پوستر رندر کن.',
                    'system_prompt' => 'You are a professional graphic designer AI specialized in advertising posters with accurate embedded text rendering.',
                    'negative_prompt' => 'blurry text, misspelled words, low resolution, cluttered layout',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'business_name', 'label_fa' => 'نام کسب‌وکار', 'type' => 'text', 'required' => true],
                        ['name' => 'style', 'label_fa' => 'سبک طراحی', 'type' => 'select', 'required' => true, 'options' => ['مدرن', 'لوکس', 'مینیمال', 'رنگارنگ']],
                        ['name' => 'offer_text', 'label_fa' => 'متن تخفیف / پیشنهاد', 'type' => 'text', 'required' => false],
                    ],
                    'timeout' => 70,
                    'pipeline_type' => 'image_generation',
                    'subject_type' => 'product',
                    'identity_preservation' => false,
                    'identity_strength' => 80,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 0,
                    'max_reference_images' => 2,
                    'watermark_enabled' => false,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'subscription',
                    'credit_cost' => 0,
                    'display_mode' => 'card',
                    'card_shape' => 'portrait',
                    'gallery_layout' => 'grid',
                    'card_label' => 'اشتراک',
                    'output_type' => 'image',
                    'output_format' => 'png',
                    'output_count' => 1,
                    'resolution' => '1024×1365',
                    'aspect_ratio' => '3:4',
                    'delivery_method' => 'instant',
                    'estimated_time' => 35,
                    'price_tier' => 'standard',
                    'discount_percentage' => 0,
                    'platform' => 'both',
                    'accent_color' => '#F59E0B',
                    'explore_tiles' => ['1x1', '1x2'],
                    'new_display_order' => 2,
                    'new_internal_code' => 'BUS-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => false,
                    'new_is_recommended' => true,
                    'new_is_beta' => false,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => null,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => 'در اشتراک شما',
                ],
            ],

            // ── ۳) EVENTS — ویدیو دعوت عروسی (media_type=video) ──
            [
                'category_paths' => ['video/invitation-video', 'occasions/wedding'],
                'flags' => ['is_featured' => false, 'is_new' => true, 'is_trending' => true],
                'fillable' => [
                    'name_fa' => 'ویدیو دعوت‌نامه عروسی هوش مصنوعی',
                    'name_en' => 'AI Wedding Invitation Video',
                    'slug' => 'ai-wedding-invitation-video',
                    'description_fa' => 'یک ویدیوی دعوت عروسی سینمایی و احساسی با اسم عروس و داماد و تاریخ مراسم بساز — آماده ارسال در واتساپ و اینستاگرام.',
                    'description_en' => 'Create a cinematic, emotional wedding invitation video with the couple\'s names and date — ready to share on WhatsApp and Instagram.',
                    'meta_title' => 'ویدیو دعوت عروسی با هوش مصنوعی | وطن AI',
                    'meta_description' => 'ویدیوی دعوت عروسی سینمایی و شخصی‌سازی‌شده بسازید، فقط با وارد کردن اسم و تاریخ.',
                    'meta_keywords' => 'دعوت عروسی, ویدیو مناسبتی, هوش مصنوعی, عروسی',
                    'category' => 'EVENTS',
                    'subcategory' => 'Wedding',
                    'status' => 'active',
                    'tags' => ['عروسی', 'دعوت‌نامه', 'ویدیو', 'مناسبتی'],
                    'thumbnail' => 'products/thumbnails/sample-wedding-style.jpg',
                    'cover' => 'products/thumbnails/sample-wedding-style.jpg',
                    'sample_outputs' => ['products/samples/ai-wedding-invitation-video-1.mp4', 'products/samples/ai-wedding-invitation-video-2.avif'],
                    'media_type' => 'video',
                    'preview_video_url' => 'products/samples/ai-wedding-invitation-video-1.mp4',
                    'primary_model' => 'kwaivgi/kling-v2.5-turbo',
                    'fallback_models' => ['luma/dream-machine-2'],
                    'prompt_template' => 'یک ویدیوی دعوت عروسی سینمایی با نام‌های {names} و تاریخ {date} با سبک {style} بساز.',
                    'system_prompt' => 'You are a cinematic video generation AI specialized in emotional wedding invitation clips.',
                    'negative_prompt' => 'shaky footage, distorted text, low quality',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'names', 'label_fa' => 'اسم عروس و داماد', 'type' => 'text', 'required' => true],
                        ['name' => 'date', 'label_fa' => 'تاریخ مراسم', 'type' => 'date', 'required' => true],
                        ['name' => 'style', 'label_fa' => 'سبک ویدیو', 'type' => 'select', 'required' => true, 'options' => ['سینمایی', 'رمانتیک', 'مدرن']],
                    ],
                    'timeout' => 180,
                    'pipeline_type' => 'video_generation',
                    'subject_type' => 'scene',
                    'identity_preservation' => false,
                    'identity_strength' => 80,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 0,
                    'max_reference_images' => 2,
                    'watermark_enabled' => true,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'per_credit',
                    'credit_cost' => 40,
                    'display_mode' => 'card',
                    'card_shape' => 'portrait',
                    'gallery_layout' => 'grid',
                    'card_label' => 'ویدیویی',
                    'output_type' => 'video',
                    'output_format' => 'mp4',
                    'output_count' => 1,
                    'resolution' => '1080×1920',
                    'aspect_ratio' => '9:16',
                    'delivery_method' => 'queued',
                    'estimated_time' => 90,
                    'price_tier' => 'standard',
                    'discount_percentage' => 10,
                    'platform' => 'both',
                    'accent_color' => '#EF4444',
                    'explore_tiles' => ['1x2', '2x2'],
                    'new_display_order' => 3,
                    'new_internal_code' => 'EVT-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => false,
                    'new_is_recommended' => false,
                    'new_is_beta' => false,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => 5,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => null,
                ],
            ],

            // ── ۴) FAMILY — عکس هنری خانوادگی ──
            [
                'category_paths' => ['portrait/family'],
                'flags' => ['is_featured' => false, 'is_new' => true, 'is_trending' => false],
                'fillable' => [
                    'name_fa' => 'عکس هنری خانوادگی با هوش مصنوعی',
                    'name_en' => 'AI Artistic Family Portrait',
                    'slug' => 'ai-family-portrait',
                    'description_fa' => 'عکس دورهمی خانواده را به یک پرتره هنری با نورپردازی گرم تبدیل کن، با حفظ کامل چهره‌ی همه اعضا.',
                    'description_en' => 'Turn a casual family photo into a warm, artistic portrait while preserving every family member\'s exact likeness.',
                    'meta_title' => 'عکس هنری خانوادگی با هوش مصنوعی | وطن AI',
                    'meta_description' => 'عکس خانوادگی خود را به یک پرتره هنری و حرفه‌ای تبدیل کنید.',
                    'meta_keywords' => 'عکس خانوادگی, پرتره خانواده, هوش مصنوعی',
                    'category' => 'FAMILY',
                    'subcategory' => 'Family Portrait',
                    'status' => 'active',
                    'tags' => ['خانواده', 'پرتره', 'هنری'],
                    'thumbnail' => 'products/thumbnails/ai-family-portrait.jpg',
                    'cover' => 'products/thumbnails/ai-family-portrait.jpg',
                    'sample_outputs' => ['products/samples/ai-family-portrait-1.jpg', 'products/samples/ai-family-portrait-2.webp'],
                    'media_type' => 'photo',
                    'preview_video_url' => null,
                    'primary_model' => 'openai/gpt-image-1',
                    'fallback_models' => ['google/gemini-3.1-flash-image'],
                    'prompt_template' => 'یک عکس خانوادگی هنری در {setting} با حس‌وحال {mood} بساز، چهره همه اعضای خانواده دقیقاً حفظ شود.',
                    'system_prompt' => 'You are a family portrait photography AI. Preserve the exact facial identity of every person present in the reference image.',
                    'negative_prompt' => 'distorted faces, extra people, low quality',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'setting', 'label_fa' => 'لوکیشن', 'type' => 'select', 'required' => true, 'options' => ['پارک', 'خانه', 'استودیو', 'ساحل']],
                        ['name' => 'mood', 'label_fa' => 'حس و حال', 'type' => 'select', 'required' => false, 'options' => ['گرم و صمیمی', 'رسمی', 'شاد']],
                    ],
                    'timeout' => 65,
                    'pipeline_type' => 'image_generation',
                    'subject_type' => 'face',
                    'identity_preservation' => true,
                    'identity_strength' => 88,
                    'preserve_body' => true,
                    'identity_instructions' => 'Preserve the exact facial identity and body proportions of every family member visible in the reference photo.',
                    'min_reference_images' => 2,
                    'max_reference_images' => 6,
                    'watermark_enabled' => true,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'per_credit',
                    'credit_cost' => 18,
                    'display_mode' => 'card',
                    'card_shape' => 'portrait',
                    'gallery_layout' => 'grid',
                    'card_label' => null,
                    'output_type' => 'image',
                    'output_format' => 'jpg',
                    'output_count' => 1,
                    'resolution' => '1024×1365',
                    'aspect_ratio' => '3:4',
                    'delivery_method' => 'instant',
                    'estimated_time' => 30,
                    'price_tier' => 'standard',
                    'discount_percentage' => 0,
                    'platform' => 'both',
                    'accent_color' => '#14B8A6',
                    'explore_tiles' => ['1x1', '2x2', '1x2'],
                    'new_display_order' => 4,
                    'new_internal_code' => 'FAM-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => false,
                    'new_is_recommended' => false,
                    'new_is_beta' => false,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => null,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => null,
                ],
            ],

            // ── ۵) KIDS — نقاشی فانتزی کودکانه (رایگان) ──
            [
                'category_paths' => ['portrait/kids', 'styles/fantasy'],
                'flags' => ['is_featured' => false, 'is_new' => false, 'is_trending' => false],
                'fillable' => [
                    'name_fa' => 'تبدیل عکس کودک به نقاشی فانتزی',
                    'name_en' => 'AI Kids Fantasy Painting',
                    'slug' => 'ai-kids-fantasy-painting',
                    'description_fa' => 'عکس کودک را به یک نقاشی فانتزی رنگارنگ و رویایی تبدیل کن — کاملاً رایگان.',
                    'description_en' => 'Turn your kid\'s photo into a colorful, dreamy fantasy painting — completely free.',
                    'meta_title' => 'نقاشی فانتزی کودکانه با هوش مصنوعی | وطن AI',
                    'meta_description' => 'عکس فرزند خود را به یک نقاشی فانتزی زیبا تبدیل کنید، رایگان و در چند ثانیه.',
                    'meta_keywords' => 'نقاشی کودک, فانتزی, هوش مصنوعی, رایگان',
                    'category' => 'KIDS',
                    'subcategory' => 'Fantasy',
                    'status' => 'active',
                    'tags' => ['کودک', 'فانتزی', 'نقاشی', 'رایگان'],
                    'thumbnail' => 'products/thumbnails/sample-photo-to-paint.jpg',
                    'cover' => 'products/thumbnails/sample-photo-to-paint.jpg',
                    'sample_outputs' => ['products/samples/ai-kids-fantasy-painting-1.webp', 'products/samples/ai-kids-fantasy-painting-2.webp'],
                    'media_type' => 'photo',
                    'preview_video_url' => null,
                    'primary_model' => 'google/gemini-3.1-flash-lite-image',
                    'fallback_models' => ['openai/gpt-image-1-mini'],
                    'prompt_template' => 'عکس کودک را به یک نقاشی فانتزی با سبک {art_style} تبدیل کن، فضای رنگارنگ و رویایی بساز.',
                    'system_prompt' => null,
                    'negative_prompt' => 'scary, dark, realistic gore',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'art_style', 'label_fa' => 'سبک نقاشی', 'type' => 'select', 'required' => true, 'options' => ['آبرنگ', 'کارتونی', 'فانتزی جادویی', 'انیمه']],
                    ],
                    'timeout' => 45,
                    'pipeline_type' => 'image_generation',
                    'subject_type' => 'face',
                    'identity_preservation' => true,
                    'identity_strength' => 70,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 1,
                    'max_reference_images' => 2,
                    'watermark_enabled' => true,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'free',
                    'credit_cost' => 0,
                    'display_mode' => 'card',
                    'card_shape' => 'portrait',
                    'gallery_layout' => 'grid',
                    'card_label' => 'رایگان',
                    'output_type' => 'image',
                    'output_format' => 'png',
                    'output_count' => 1,
                    'resolution' => '1024×1024',
                    'aspect_ratio' => '1:1',
                    'delivery_method' => 'instant',
                    'estimated_time' => 15,
                    'price_tier' => 'free',
                    'discount_percentage' => 0,
                    'platform' => 'both',
                    'accent_color' => '#A855F7',
                    'explore_tiles' => ['1x1'],
                    'new_display_order' => 5,
                    'new_internal_code' => 'KID-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => false,
                    'new_is_recommended' => false,
                    'new_is_beta' => false,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => 3,
                    'new_show_free_badge' => true,
                    'new_price_custom_label' => null,
                ],
            ],

            // ── ۶) PETS — پرتره هنری حیوان خانگی ──
            [
                'category_paths' => ['portrait'],
                'flags' => ['is_featured' => false, 'is_new' => true, 'is_trending' => true],
                'fillable' => [
                    'name_fa' => 'پرتره هنری حیوان خانگی با هوش مصنوعی',
                    'name_en' => 'AI Pet Portrait Studio',
                    'slug' => 'ai-pet-portrait',
                    'description_fa' => 'یک پرتره هنری و حرفه‌ای از حیوان خانگی‌تان بساز، با جزئیات دقیق فر و طبیعی حیوان.',
                    'description_en' => 'Create a professional, artistic portrait of your pet with accurate, natural fur detail.',
                    'meta_title' => 'پرتره حیوان خانگی با هوش مصنوعی | وطن AI',
                    'meta_description' => 'عکس حیوان خانگی خود را به یک پرتره هنری حرفه‌ای تبدیل کنید.',
                    'meta_keywords' => 'پرتره حیوان خانگی, عکس سگ, عکس گربه, هوش مصنوعی',
                    'category' => 'PETS',
                    'subcategory' => 'Pet Portrait',
                    'status' => 'active',
                    'tags' => ['حیوان خانگی', 'پرتره', 'هنری'],
                    'thumbnail' => 'products/thumbnails/ai-pet-portrait.avif',
                    'cover' => 'products/thumbnails/ai-pet-portrait.avif',
                    'sample_outputs' => ['products/samples/ai-pet-portrait-1.jpeg', 'products/samples/ai-pet-portrait-2.webp'],
                    'media_type' => 'photo',
                    'preview_video_url' => null,
                    'primary_model' => 'google/gemini-3-pro-image',
                    'fallback_models' => ['sourceful/riverflow-v2.5-pro'],
                    'prompt_template' => 'یک پرتره هنری حرفه‌ای از {pet_type} با سبک عکاسی {style} بساز، جزئیات فر و ظاهر طبیعی حیوان دقیق حفظ شود.',
                    'system_prompt' => 'You are a professional pet photography AI with attention to fur texture and natural animal features.',
                    'negative_prompt' => 'cartoonish, distorted anatomy, low quality',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'pet_type', 'label_fa' => 'نوع حیوان', 'type' => 'select', 'required' => true, 'options' => ['سگ', 'گربه', 'اسب', 'پرنده', 'سایر']],
                        ['name' => 'style', 'label_fa' => 'سبک عکاسی', 'type' => 'select', 'required' => false, 'options' => ['استودیویی', 'طبیعت', 'فانتزی']],
                    ],
                    'timeout' => 55,
                    'pipeline_type' => 'image_generation',
                    'subject_type' => 'generic',
                    'identity_preservation' => false,
                    'identity_strength' => 80,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 1,
                    'max_reference_images' => 2,
                    'watermark_enabled' => true,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'per_credit',
                    'credit_cost' => 10,
                    'display_mode' => 'card',
                    'card_shape' => 'portrait',
                    'gallery_layout' => 'grid',
                    'card_label' => 'ترند',
                    'output_type' => 'image',
                    'output_format' => 'jpg',
                    'output_count' => 1,
                    'resolution' => '1024×1024',
                    'aspect_ratio' => '1:1',
                    'delivery_method' => 'instant',
                    'estimated_time' => 25,
                    'price_tier' => 'standard',
                    'discount_percentage' => 0,
                    'platform' => 'both',
                    'accent_color' => '#F59E0B',
                    'explore_tiles' => ['1x1', '2x2'],
                    'new_display_order' => 6,
                    'new_internal_code' => 'PET-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => false,
                    'new_is_recommended' => false,
                    'new_is_beta' => false,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => null,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => null,
                ],
            ],

            // ── ۷) ENTERTAINMENT — ویدیوی کوتاه سینمایی (media_type=video) ──
            [
                'category_paths' => ['video/cinematic-video'],
                'flags' => ['is_featured' => true, 'is_new' => true, 'is_trending' => true],
                'fillable' => [
                    'name_fa' => 'ویدیوی کوتاه سینمایی هوش مصنوعی',
                    'name_en' => 'AI Cinematic Short Video',
                    'slug' => 'ai-cinematic-short-video',
                    'description_fa' => 'یک ویدیوی کوتاه با کیفیت سینمایی هالیوودی، حرکت دوربین طبیعی و نورپردازی حرفه‌ای بساز.',
                    'description_en' => 'Generate a short video with Hollywood-grade cinematic quality, natural camera movement and professional lighting.',
                    'meta_title' => 'ویدیوی سینمایی هوش مصنوعی | وطن AI',
                    'meta_description' => 'ویدیوی کوتاه سینمایی با کیفیت بالا بسازید — اکشن، درام، فانتزی یا علمی‌تخیلی.',
                    'meta_keywords' => 'ویدیو سینمایی, هوش مصنوعی, تولید ویدیو',
                    'category' => 'ENTERTAINMENT',
                    'subcategory' => 'Cinematic',
                    'status' => 'active',
                    'tags' => ['سینمایی', 'ویدیو', 'سرگرمی'],
                    'thumbnail' => 'products/thumbnails/ai-cinematic-short-video.jpg',
                    'cover' => 'products/thumbnails/ai-cinematic-short-video.jpg',
                    'sample_outputs' => ['products/samples/ai-cinematic-short-video-1.mp4', 'products/samples/ai-cinematic-short-video-2.webp'],
                    'media_type' => 'video',
                    'preview_video_url' => 'products/samples/ai-cinematic-short-video-1.mp4',
                    'primary_model' => 'runwayml/gen-4-turbo',
                    'fallback_models' => ['kwaivgi/kling-v2.5-turbo'],
                    'prompt_template' => 'یک ویدیوی کوتاه سینمایی با موضوع {theme} و مدت زمان {duration} ثانیه با کیفیت هالیوودی بساز.',
                    'system_prompt' => 'You are a cinematic video generation AI with professional camera work and lighting.',
                    'negative_prompt' => 'low resolution, choppy motion, watermark',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'theme', 'label_fa' => 'موضوع ویدیو', 'type' => 'select', 'required' => true, 'options' => ['اکشن', 'درام', 'فانتزی', 'علمی‌تخیلی']],
                        ['name' => 'duration', 'label_fa' => 'مدت زمان (ثانیه)', 'type' => 'select', 'required' => true, 'options' => ['5', '10', '15']],
                    ],
                    'timeout' => 200,
                    'pipeline_type' => 'video_generation',
                    'subject_type' => 'scene',
                    'identity_preservation' => false,
                    'identity_strength' => 80,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 0,
                    'max_reference_images' => 1,
                    'watermark_enabled' => false,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'per_credit',
                    'credit_cost' => 50,
                    'display_mode' => 'card',
                    'card_shape' => 'landscape',
                    'gallery_layout' => 'grid',
                    'card_label' => 'پرمیوم',
                    'output_type' => 'video',
                    'output_format' => 'mp4',
                    'output_count' => 1,
                    'resolution' => '1920×1080',
                    'aspect_ratio' => '16:9',
                    'delivery_method' => 'queued',
                    'estimated_time' => 120,
                    'price_tier' => 'premium',
                    'discount_percentage' => 0,
                    'platform' => 'both',
                    'accent_color' => '#8B5CF6',
                    'explore_tiles' => ['2x1', '2x2'],
                    'new_display_order' => 7,
                    'new_internal_code' => 'ENT-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => true,
                    'new_is_recommended' => true,
                    'new_is_beta' => true,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => 3,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => null,
                ],
            ],

            // ── ۸) PRODUCTS — عکاسی حرفه‌ای محصول ──
            [
                'category_paths' => ['business/product-photo'],
                'flags' => ['is_featured' => true, 'is_new' => false, 'is_trending' => false],
                'fillable' => [
                    'name_fa' => 'عکاسی حرفه‌ای محصول با هوش مصنوعی',
                    'name_en' => 'AI Product Photography',
                    'slug' => 'ai-product-photography',
                    'description_fa' => 'عکس ساده محصول را به یک عکاسی استودیویی حرفه‌ای با پس‌زمینه دلخواه تبدیل کن.',
                    'description_en' => 'Turn a simple product photo into a professional studio shot with a custom background.',
                    'meta_title' => 'عکاسی محصول با هوش مصنوعی | وطن AI',
                    'meta_description' => 'عکس محصولات خود را با کیفیت استودیویی و پس‌زمینه دلخواه بازسازی کنید.',
                    'meta_keywords' => 'عکاسی محصول, عکس فروشگاهی, هوش مصنوعی',
                    'category' => 'PRODUCTS',
                    'subcategory' => 'Product Photography',
                    'status' => 'active',
                    'tags' => ['محصول', 'عکاسی', 'فروشگاه'],
                    'thumbnail' => 'products/thumbnails/sample-bg-remove.jpg',
                    'cover' => 'products/thumbnails/sample-bg-remove.jpg',
                    'sample_outputs' => ['products/samples/ai-product-photography-1.avif', 'products/samples/ai-product-photography-2.webp'],
                    'media_type' => 'photo',
                    'preview_video_url' => null,
                    'primary_model' => 'openai/gpt-image-2',
                    'fallback_models' => ['sourceful/riverflow-v2.5-pro', 'google/gemini-3-pro-image'],
                    'prompt_template' => 'عکس محصول را با پس‌زمینه {background} و زاویه دوربین {angle} به‌صورت عکاسی حرفه‌ای استودیویی بازسازی کن.',
                    'system_prompt' => 'You are a professional e-commerce product photography AI.',
                    'negative_prompt' => 'distorted product shape, wrong colors, low quality',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'background', 'label_fa' => 'پس‌زمینه', 'type' => 'select', 'required' => true, 'options' => ['سفید استودیویی', 'چوبی طبیعی', 'سنگ مرمر', 'گرادیانت رنگی']],
                        ['name' => 'angle', 'label_fa' => 'زاویه دوربین', 'type' => 'select', 'required' => false, 'options' => ['از بالا', 'از روبرو', '۴۵ درجه']],
                    ],
                    'timeout' => 50,
                    'pipeline_type' => 'image_generation',
                    'subject_type' => 'product',
                    'identity_preservation' => false,
                    'identity_strength' => 80,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 1,
                    'max_reference_images' => 1,
                    'watermark_enabled' => true,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'per_credit',
                    'credit_cost' => 8,
                    'display_mode' => 'card',
                    'card_shape' => 'square',
                    'gallery_layout' => 'grid',
                    'card_label' => null,
                    'output_type' => 'image',
                    'output_format' => 'jpg',
                    'output_count' => 3,
                    'resolution' => '1024×1024',
                    'aspect_ratio' => '1:1',
                    'delivery_method' => 'instant',
                    'estimated_time' => 20,
                    'price_tier' => 'standard',
                    'discount_percentage' => 0,
                    'platform' => 'both',
                    'accent_color' => '#0EA5E9',
                    'explore_tiles' => ['1x1'],
                    'new_display_order' => 8,
                    'new_internal_code' => 'PRD-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => false,
                    'new_is_recommended' => false,
                    'new_is_beta' => false,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => null,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => null,
                ],
            ],

            // ── ۹) AVATARS — آواتار انیمه ──
            [
                'category_paths' => ['portrait/anime', 'styles/anime'],
                'flags' => ['is_featured' => false, 'is_new' => true, 'is_trending' => true],
                'fillable' => [
                    'name_fa' => 'آواتار انیمه هوش مصنوعی',
                    'name_en' => 'AI Anime Avatar Generator',
                    'slug' => 'ai-anime-avatar',
                    'description_fa' => 'چهره‌ی خود را به یک کاراکتر انیمه با سبک دلخواه تبدیل کن — مناسب پروفایل شبکه‌های اجتماعی.',
                    'description_en' => 'Turn your face into an anime-style character avatar — perfect for social media profiles.',
                    'meta_title' => 'ساخت آواتار انیمه با هوش مصنوعی | وطن AI',
                    'meta_description' => 'آواتار انیمه اختصاصی خود را در چند ثانیه بسازید.',
                    'meta_keywords' => 'آواتار انیمه, پروفایل انیمه, هوش مصنوعی',
                    'category' => 'AVATARS',
                    'subcategory' => 'Anime',
                    'status' => 'active',
                    'tags' => ['آواتار', 'انیمه', 'کاراکتر'],
                    'thumbnail' => 'products/thumbnails/ai-anime-avatar.webp',
                    'cover' => 'products/thumbnails/ai-anime-avatar.webp',
                    'sample_outputs' => ['products/samples/ai-anime-avatar-1.webp', 'products/samples/ai-anime-avatar-2.webp'],
                    'media_type' => 'photo',
                    'preview_video_url' => null,
                    'primary_model' => 'google/gemini-3.1-flash-image-preview',
                    'fallback_models' => ['openai/gpt-image-1-mini'],
                    'prompt_template' => 'چهره کاربر را به یک آواتار انیمه با سبک {anime_style} و لباس {outfit} تبدیل کن.',
                    'system_prompt' => 'You are an anime-style avatar generation AI.',
                    'negative_prompt' => 'realistic photo, distorted face, low quality',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'anime_style', 'label_fa' => 'سبک انیمه', 'type' => 'select', 'required' => true, 'options' => ['شونن', 'چیبی', 'سایبرپانک', 'استودیو جیبلی']],
                        ['name' => 'outfit', 'label_fa' => 'لباس کاراکتر', 'type' => 'text', 'required' => false],
                    ],
                    'timeout' => 40,
                    'pipeline_type' => 'image_generation',
                    'subject_type' => 'face',
                    'identity_preservation' => true,
                    'identity_strength' => 60,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 1,
                    'max_reference_images' => 1,
                    'watermark_enabled' => true,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'per_credit',
                    'credit_cost' => 12,
                    'display_mode' => 'card',
                    'card_shape' => 'square',
                    'gallery_layout' => 'grid',
                    'card_label' => 'بتا',
                    'output_type' => 'image',
                    'output_format' => 'png',
                    'output_count' => 2,
                    'resolution' => '1024×1024',
                    'aspect_ratio' => '1:1',
                    'delivery_method' => 'instant',
                    'estimated_time' => 20,
                    'price_tier' => 'standard',
                    'discount_percentage' => 0,
                    'platform' => 'both',
                    'accent_color' => '#6366F1',
                    'explore_tiles' => ['1x1', '2x2'],
                    'new_display_order' => 9,
                    'new_internal_code' => 'AVT-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder',
                    'new_is_premium' => false,
                    'new_is_recommended' => false,
                    'new_is_beta' => true,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => null,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => null,
                ],
            ],

            // ── ۱۰) VIDEOS — ریلز تبلیغاتی اینستاگرام (media_type=both) ──
            [
                'category_paths' => ['video/instagram-video', 'social/instagram/reels-cover'],
                'flags' => ['is_featured' => false, 'is_new' => true, 'is_trending' => false, 'multi_step_pipeline' => true],
                'fillable' => [
                    'name_fa' => 'ریلز تبلیغاتی هوش مصنوعی',
                    'name_en' => 'AI Instagram Reels Ad Generator',
                    'slug' => 'ai-instagram-reels-ad',
                    'description_fa' => 'یک ریلز تبلیغاتی کوتاه به‌همراه کاور جذاب برای برند یا محصول خود بساز — همزمان عکس و ویدیو.',
                    'description_en' => 'Create a short promotional reel with an eye-catching cover for your brand or product — both image and video output.',
                    'meta_title' => 'ریلز تبلیغاتی اینستاگرام با هوش مصنوعی | وطن AI',
                    'meta_description' => 'ریلز تبلیغاتی حرفه‌ای برای اینستاگرام بسازید، به‌همراه کاور اختصاصی.',
                    'meta_keywords' => 'ریلز اینستاگرام, ویدیو تبلیغاتی, هوش مصنوعی',
                    'category' => 'VIDEOS',
                    'subcategory' => 'Reels',
                    'status' => 'active',
                    'tags' => ['ریلز', 'اینستاگرام', 'تبلیغات', 'ویدیو'],
                    'thumbnail' => 'products/thumbnails/ai-instagram-reels-ad.webp',
                    'cover' => 'products/thumbnails/ai-instagram-reels-ad.webp',
                    'sample_outputs' => ['products/samples/ai-instagram-reels-ad-1.mp4', 'products/samples/ai-instagram-reels-ad-2.mp4'],
                    'media_type' => 'both',
                    'preview_video_url' => 'products/samples/ai-instagram-reels-ad-1.mp4',
                    'primary_model' => 'luma/dream-machine-2',
                    'fallback_models' => ['kwaivgi/kling-v2.5-turbo', 'google/gemini-3.1-flash-image'],
                    'prompt_template' => 'یک ریلز تبلیغاتی کوتاه برای {product_name} با متن فراخوان «{cta_text}» بساز، همراه با یک تصویر کاور جذاب.',
                    'system_prompt' => 'You are a social-media ad video generation AI producing short vertical reels plus a matching cover image.',
                    'negative_prompt' => 'low resolution, shaky footage, unreadable text',
                    'seed' => null,
                    'provider_options' => null,
                    'input_schema' => [
                        ['name' => 'product_name', 'label_fa' => 'نام محصول/برند', 'type' => 'text', 'required' => true],
                        ['name' => 'cta_text', 'label_fa' => 'متن فراخوان به اقدام', 'type' => 'text', 'required' => false],
                    ],
                    'timeout' => 150,
                    'pipeline_type' => 'video_generation',
                    'subject_type' => 'product',
                    'identity_preservation' => false,
                    'identity_strength' => 80,
                    'preserve_body' => false,
                    'identity_instructions' => null,
                    'min_reference_images' => 0,
                    'max_reference_images' => 3,
                    'watermark_enabled' => false,
                    'watermark_position' => 'corner',
                    'pricing_model' => 'subscription',
                    'credit_cost' => 0,
                    'display_mode' => 'card',
                    'card_shape' => 'portrait',
                    'gallery_layout' => 'grid',
                    'card_label' => 'اشتراک',
                    'output_type' => 'video',
                    'output_format' => 'mp4',
                    'output_count' => 1,
                    'resolution' => '1080×1920',
                    'aspect_ratio' => '9:16',
                    'delivery_method' => 'queued',
                    'estimated_time' => 60,
                    'price_tier' => 'standard',
                    'discount_percentage' => 0,
                    'platform' => 'mobile',
                    'accent_color' => '#8B5CF6',
                    'explore_tiles' => ['1x2', '2x2'],
                    'new_display_order' => 10,
                    'new_internal_code' => 'VID-001',
                    'new_admin_note' => 'محصول نمونه تست لوکال — Seeder (multi_step_pipeline: تولید کاور + ویدیو)',
                    'new_is_premium' => false,
                    'new_is_recommended' => false,
                    'new_is_beta' => false,
                    'new_min_credit_required' => 0,
                    'new_max_run_per_user' => null,
                    'new_show_free_badge' => false,
                    'new_price_custom_label' => 'در اشتراک شما',
                ],
            ],

        ];
    }
}
