<div class="v2-modern-social-stack" id="v2-step-three-modern">
  <section class="v2-modern-social-row" aria-labelledby="v2-modern-instagram-title">
    <div class="v2-modern-social-config">
      <div class="v2-modern-social-head"><label id="v2-modern-instagram-title"><input type="checkbox" name="instagram_enabled" value="1" checked><i class="fa-brands fa-instagram"></i> اینستاگرام</label><span class="v2-social-topic">تاپیک ۴</span></div>
      <div class="v2-modern-caption-block"><div class="v2-modern-caption-head"><strong>سه مدل کپشن اینستاگرام</strong><div class="v2-platform-actions"><button type="button" class="v2-mini-btn" data-v2-prompt-settings="instagram"><i class="fa-solid fa-sliders"></i> تنظیمات کپشن</button><button type="button" class="v2-mini-btn" data-v2-modern-generate="instagram"><i class="fa-solid fa-wand-magic-sparkles"></i> ساخت کپشن</button></div></div><div class="v2-modern-caption-options" id="v2-modern-caption-options-instagram">@for($captionIndex=1;$captionIndex<=3;$captionIndex++)<button type="button" class="v2-modern-caption-option" disabled><small>گزینه {{ $captionIndex }}</small>برای ساخت سه کپشن، دکمهٔ ساخت کپشن را بزنید.</button>@endfor</div><textarea class="v2-textarea" id="v2-modern-instagram-caption" name="caption_text" placeholder="کپشن انتخابی اینستاگرام..."></textarea></div>
      <div class="v2-modern-caption-block"><div class="v2-modern-caption-head"><strong>کلمهٔ کلیدی و پاسخ دایرکت</strong><button type="button" class="v2-mini-btn" data-v2-modern-keyword="instagram"><i class="fa-solid fa-key"></i> ساخت کلمه کلیدی</button></div><div class="v2-modern-caption-options" id="v2-modern-keyword-options">@for($keywordIndex=1;$keywordIndex<=3;$keywordIndex++)<button type="button" class="v2-modern-caption-option" disabled><small>گزینه {{ $keywordIndex }}</small>برای ساخت پیشنهادها، دکمهٔ ساخت کلمه کلیدی را بزنید.</button>@endfor</div><div class="v2-keyword-fields"><input class="v2-input" id="v2-modern-instagram-keyword" name="keyword" placeholder="کلمه کلیدی"><textarea class="v2-textarea" id="v2-modern-instagram-dm-template" name="dm_template" placeholder="پاسخ آمادهٔ دایرکت..."></textarea></div></div>
      <div class="v2-platform-delivery"><label><input type="checkbox" name="instagram_send_video" value="1" checked> ارسال ویدیوی نهایی</label><label><input type="checkbox" name="instagram_send_images" value="1"> ارسال عکس‌های محصول</label></div>
    </div>
    <aside class="v2-modern-social-preview" aria-label="پیش‌نمایش اینستاگرام"><div class="v2-modern-social-phone"><div class="v2-modern-social-screen"><div class="v2-modern-instagram-head"><span class="v2-modern-instagram-avatar"></span> وطن استودیو</div>@if($productImages->first())<img class="v2-modern-instagram-media" src="{{ $productImages->first()['url'] }}" alt="تصویر محصول">@else<div class="v2-modern-instagram-media"></div>@endif<div class="v2-modern-instagram-copy" id="v2-modern-instagram-preview-caption">کپشن اینستاگرام اینجا پیش‌نمایش داده می‌شود.</div></div><img class="v2-modern-social-frame" src="{{ asset('admin/images/video-studio/iphone-hook-frame.png') }}" alt="قاب پیش‌نمایش اینستاگرام"></div></aside>
  </section>

  <section class="v2-modern-social-row" aria-labelledby="v2-modern-telegram-title">
    <div class="v2-modern-social-config">
      <div class="v2-modern-social-head"><label id="v2-modern-telegram-title"><input type="checkbox" name="telegram_enabled" value="1" checked><i class="fa-brands fa-telegram"></i> تلگرام</label><span class="v2-social-topic">تاپیک ۲</span></div>
      <div class="v2-modern-caption-block"><div class="v2-modern-caption-head"><strong>سه مدل کپشن تلگرام</strong><div class="v2-platform-actions"><button type="button" class="v2-mini-btn" data-v2-prompt-settings="telegram"><i class="fa-solid fa-sliders"></i> تنظیمات کپشن</button><button type="button" class="v2-mini-btn" data-v2-modern-generate="telegram"><i class="fa-solid fa-wand-magic-sparkles"></i> ساخت کپشن</button></div></div><div class="v2-modern-caption-options" id="v2-modern-caption-options-telegram">@for($captionIndex=1;$captionIndex<=3;$captionIndex++)<button type="button" class="v2-modern-caption-option" disabled><small>گزینه {{ $captionIndex }}</small>برای ساخت سه کپشن، دکمهٔ ساخت کپشن را بزنید.</button>@endfor</div><textarea class="v2-textarea" id="v2-modern-telegram-caption" name="telegram_caption_text" placeholder="کپشن انتخابی تلگرام..."></textarea></div>
      <div class="v2-telegram-buttons"><div class="v2-telegram-buttons-head"><span><i class="fa-solid fa-link"></i> دکمه‌های رنگی زیر کپشن</span><label class="v2-checkbox-label"><input type="checkbox" name="telegram_buttons_enabled" value="1" checked> فعال</label></div><div class="v2-telegram-button-list" id="v2-modern-telegram-button-list"><div class="v2-telegram-button-row" data-v2-modern-telegram-button-row><input class="v2-input" name="telegram_button_label[]" placeholder="متن دکمه"><input class="v2-input" type="url" name="telegram_button_url[]" placeholder="https://..."><select class="v2-select" name="telegram_button_style[]"><option value="primary">سبز وطن</option><option value="success">سبز موفق</option><option value="danger">قرمز</option></select><input type="hidden" name="telegram_button_width[]" value="full"><button class="v2-telegram-button-remove" type="button" data-v2-modern-remove-button aria-label="حذف دکمه"><i class="fa-solid fa-trash"></i></button></div></div><button class="v2-mini-btn" type="button" id="v2-modern-add-telegram-button"><i class="fa-solid fa-plus"></i> افزودن دکمه</button></div>
      <div class="v2-platform-delivery"><label><input type="checkbox" name="telegram_send_video" value="1" checked> ارسال ویدیوی نهایی</label><label><input type="checkbox" name="telegram_send_images" value="1"> ارسال عکس‌های محصول</label></div>
    </div>
    <aside class="v2-modern-social-preview" aria-label="پیش‌نمایش تلگرام"><div class="v2-modern-social-phone"><div class="v2-modern-social-screen"><div class="v2-modern-telegram-head"><span class="v2-modern-telegram-avatar"><i class="fa-brands fa-telegram"></i></span> کانال وطن</div><div class="v2-modern-telegram-chat"><div class="v2-modern-telegram-post">@if($productImages->first())<img class="v2-modern-telegram-media" src="{{ $productImages->first()['url'] }}" alt="تصویر محصول">@else<div class="v2-modern-telegram-media"></div>@endif<div class="v2-modern-telegram-copy" id="v2-modern-telegram-preview-caption">کپشن تلگرام اینجا پیش‌نمایش داده می‌شود.</div><div class="v2-modern-telegram-buttons" id="v2-modern-telegram-preview-buttons"></div></div></div></div><img class="v2-modern-social-frame" src="{{ asset('admin/images/video-studio/iphone-hook-frame.png') }}" alt="قاب پیش‌نمایش تلگرام"></div></aside>
  </section>
</div>
