<section class="create-panel create-form-panel" data-creator-panel>
  <div class="create-panel-heading"><div><span class="create-step">استودیوی ساخت وطن</span><h2 data-creator-title>{{ isset($sitePage) && $sitePage->content('show_page_title', true) ? $sitePage->title : 'چی می‌خوای برات انجام بدم؟' }}</h2><p data-creator-subtitle>{{ isset($sitePage) && $sitePage->content('show_page_title', true) ? $sitePage->subtitle : 'ایده‌ات را بنویس و با وطن شروع کن.' }}</p></div><button type="button" class="create-icon-btn" data-reset-form aria-label="پاک کردن فرم" title="پاک کردن فرم"><i class="fa-solid fa-rotate-left"></i></button></div>

  <div class="create-prompt-wrap"><label for="create-prompt">توضیح ایده</label><div class="create-prompt-box"><textarea id="create-prompt" rows="5" data-prompt-input placeholder="مثلاً: یک پرتره‌ی سینمایی از یک زن ایرانی در کوچه‌های بارانی تهران، نور نئون و حال‌وهوای فیلم‌های نوآر..."></textarea><div class="create-prompt-tools"><button type="button" class="create-ghost-btn" data-prompt-improve><i class="fa-solid fa-wand-magic-sparkles"></i> بهبود پرامپت</button><span class="create-counter"><b data-prompt-count>۰</b> / ۱۰۰۰</span></div></div><div class="create-suggestion-row"><button type="button" data-suggestion="یک پوستر مینیمال برای یک رویداد موسیقی طراحی کن">پوستر مینیمال</button><button type="button" data-suggestion="یک فضای داخلی گرم و مدرن با نور صبحگاهی بساز">فضای داخلی</button><button type="button" data-suggestion="یک نمای سینمایی از تهران در شب با نورهای نئون">تهران در شب</button></div></div>

  <div class="create-upload-zone" data-upload-zone tabindex="0" role="button" aria-label="آپلود تصویر مرجع"><span class="create-upload-icon"><i class="fa-solid fa-arrow-up-from-bracket"></i></span><span class="create-upload-copy"><strong>تصویر مرجع اضافه کن</strong><small>اختیاری · برای حفظ سبک یا چهره</small></span><span class="create-upload-cta">انتخاب فایل <i class="fa-solid fa-chevron-left"></i></span><input type="file" hidden accept="image/png,image/jpeg,image/webp,video/mp4" data-upload-input></div><div class="create-upload-file" data-upload-file hidden></div>

  <div class="create-options-grid"><label class="create-field"><span>نسبت تصویر</span><select data-setting="ratio"><option>۱:۱ · مربع</option><option selected>۴:۵ · پرتره</option><option>۱۶:۹ · افقی</option><option>۹:۱۶ · عمودی</option></select></label><label class="create-field"><span>کیفیت خروجی</span><select data-setting="quality"><option>استاندارد</option><option selected>بالا · 2K</option><option>حرفه‌ای · 4K</option></select></label><label class="create-field"><span>تعداد خروجی</span><select data-setting="count"><option selected>۱ خروجی</option><option>۲ خروجی</option><option>۴ خروجی</option></select></label><label class="create-field" data-video-only hidden><span>مدت ویدیو</span><select><option selected>۵ ثانیه</option><option>۱۰ ثانیه</option><option>۱۵ ثانیه</option></select></label></div>

  <details class="create-advanced"><summary><span><i class="fa-solid fa-sliders"></i> تنظیمات پیشرفته</span><i class="fa-solid fa-chevron-down"></i></summary><div class="create-advanced-body"><label class="create-field"><span>مدل پیشنهادی</span><select><option>Vatan Vision · سریع</option><option>Vatan Vision · جزئیات بالا</option></select></label><label class="create-field"><span>موارد ناخواسته</span><input type="text" placeholder="مثلاً: متن، تاری، نویز"></label></div></details>

  <div class="create-submit-row"><div class="create-cost"><i class="fa-solid fa-bolt"></i><span>هزینه‌ی این ساخت</span><strong data-cost>۸ توکن</strong></div><button type="button" class="create-primary-btn" data-create-submit><span data-submit-label>بساز</span><i class="fa-solid fa-arrow-left"></i></button></div><p class="create-form-note"><i class="fa-solid fa-lock"></i> فایل‌ها خصوصی هستند و فقط برای همین پروژه استفاده می‌شوند.</p>
</section>
