@extends('layouts.admin')
@section('title','داشبورد پیامک — وطن استودیو')
@push('styles')<style>
.sms-dash{padding:24px;display:grid;gap:18px}.sms-head h1{font-size:22px;font-weight:800;color:var(--text-h)}.sms-head p{font-size:12px;color:var(--text-soft);margin-top:5px}.sms-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:9px}.sms-kpi{padding:12px;display:flex;align-items:center;gap:9px;min-width:0}.sms-kpi-icon{width:34px;height:34px;flex:0 0 34px;border-radius:10px;display:flex;align-items:center;justify-content:center;background:var(--primary-l);color:var(--primary);font-size:14px}.sms-kpi span{display:block;font-size:9px;color:var(--text-soft);white-space:nowrap}.sms-kpi b{display:block;color:var(--text-h);font-size:17px;margin-top:3px}.sms-section{padding:18px}.sms-section h2{font-size:15px;font-weight:800;color:var(--text-h);margin-bottom:13px}.sms-shortcuts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.sms-shortcut{padding:15px;border:1px solid var(--border);border-radius:12px;background:var(--input-bg);text-decoration:none;display:flex;align-items:center;gap:11px;color:var(--text-main)}.sms-shortcut:hover{border-color:var(--primary);color:var(--primary)}.sms-shortcut i{width:28px;text-align:center}.sms-shortcut small{display:block;color:var(--text-soft);font-size:9px;margin-top:3px}.sms-provider-row{display:flex;align-items:center;justify-content:space-between;padding:12px;border-bottom:1px solid var(--border)}.sms-dot{width:9px;height:9px;border-radius:50%;display:inline-block;margin-left:7px}.sms-dot.ok{background:var(--success)}.sms-dot.bad{background:var(--danger)}@media(max-width:1200px){.sms-kpis{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.sms-kpis,.sms-shortcuts{grid-template-columns:1fr 1fr}}@media(max-width:560px){.sms-dash{padding:14px}.sms-shortcuts,.sms-kpis{grid-template-columns:1fr}}
</style>@endpush
@section('content')<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">@include('admin.partials.header')<div class="admin-content flex-1 overflow-y-auto" id="content"><div class="sms-dash">
<div class="sms-head"><h1>داشبورد مدیریت پیامک</h1><p>نمای کلی ارسال‌ها، وضعیت سرویس‌ها و میانبرهای مدیریتی</p></div>
<div class="sms-kpis">
@foreach([['کل ارسال‌ها',$stats['sent'],'fa-paper-plane'],['ارسال امروز',$stats['today'],'fa-calendar-day'],['ارسال این هفته',$stats['week'],'fa-chart-line'],['ارسال ناموفق',$stats['failed'],'fa-triangle-exclamation'],['الگوهای فعال',$stats['templates'],'fa-file-lines'],['کمپین‌ها',$stats['campaigns'],'fa-bullhorn']] as $item)
<div class="content-card sms-kpi"><div class="sms-kpi-icon"><i class="fa-solid {{ $item[2] }}"></i></div><div><span>{{ $item[0] }}</span><b>{{ number_format($item[1]) }}</b></div></div>@endforeach
</div>
<div class="content-card sms-section"><h2>دسترسی سریع</h2><div class="sms-shortcuts">
<a class="sms-shortcut" href="{{ route('admin.sms.compose') }}"><i class="fa-solid fa-pen-to-square"></i><div>ارسال پیامک<small>ساده، گروهی و زمان‌دار</small></div></a>
<a class="sms-shortcut" href="{{ route('admin.sms.templates') }}"><i class="fa-solid fa-wand-magic-sparkles"></i><div>پیامک‌های خودکار<small>ورود، خرید، تولد و هشدارها</small></div></a>
<a class="sms-shortcut" href="{{ route('admin.sms.campaigns') }}"><i class="fa-solid fa-users-viewfinder"></i><div>مخاطبان و مناسبت‌ها<small>کمپین و دسته‌بندی مشتریان</small></div></a>
<a class="sms-shortcut" href="{{ route('admin.sms.history') }}"><i class="fa-solid fa-clock-rotate-left"></i><div>تاریخچه ارسال<small>نتیجه و وضعیت پیام‌ها</small></div></a>
@if(auth('admin')->user()?->isLeader())<a class="sms-shortcut" href="{{ route('admin.sms.providers') }}"><i class="fa-solid fa-plug"></i><div>ارائه‌دهندگان پیامک<small>API، خطوط و هشدار شارژ</small></div></a>@endif
</div></div>
<div class="content-card sms-section"><h2>وضعیت ارائه‌دهندگان</h2>@foreach($providers as $provider)<div class="sms-provider-row"><div><span class="sms-dot {{ $provider->is_active && !$provider->last_error?'ok':'bad' }}"></span><b>{{ $provider->name }}</b><small style="display:block;color:var(--text-soft);margin-top:4px">خط: {{ $provider->sender?:'تنظیم نشده' }}</small></div><div style="text-align:left"><span class="badge-pro badge-pro-{{ $provider->is_active?'success':'danger' }}">{{ $provider->is_active?'فعال':'غیرفعال' }}</span>@if(data_get($provider->settings,'last_balance'))<small style="display:block;color:var(--text-soft);margin-top:5px">اعتبار: {{ data_get($provider->settings,'last_balance') }}</small>@endif</div></div>@endforeach</div>
</div></div></main>@endsection
