@extends('layouts.admin')
@section('title', 'گزارش مقاله — وطن استودیو')
@push('styles')<link rel="stylesheet" href="{{ asset('admin/css/articles.css') }}?v={{ filemtime(public_path('admin/css/articles.css')) }}">@endpush
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px] max-[480px]:p-[14px]" id="content" dir="rtl" style="background:var(--page-bg);"><div class="article-admin">
    <header class="article-page-head"><div class="article-page-head__copy"><small>پایش عملکرد مقاله</small><h1>{{ $article->title }}</h1><p>{{ $article->category->name }} · {{ $article->author->name }} · بروزرسانی {{ $article->updated_at->diffForHumans() }}</p></div><div class="article-page-actions"><a class="article-btn" href="{{ route('admin.articles.index') }}">فهرست</a><a class="article-btn" href="{{ route('admin.articles.edit',$article) }}">ویرایش</a><a class="article-btn article-btn--primary" href="{{ $article->publicUrl() }}?preview=1" target="_blank">مشاهده مقاله</a></div></header>
    <section class="article-analytics-grid">@foreach([['بازدید کل',$article->view_count,'fa-regular fa-eye'],['بازدید یکتا',$article->unique_view_count,'fa-solid fa-user-check'],['اشتراک‌گذاری',$article->share_count,'fa-solid fa-share-nodes'],['کلیک محصول',$article->cta_click_count,'fa-solid fa-arrow-pointer'],['اسکرول ۵۰٪',$eventCounts['scroll_50'] ?? 0,'fa-solid fa-chart-simple'],['اسکرول ۹۰٪',$eventCounts['scroll_90'] ?? 0,'fa-solid fa-flag-checkered'],['کپی پرامپت',$eventCounts['prompt_copy'] ?? 0,'fa-regular fa-copy'],['دیدگاه تأییدشده',$article->comments_count,'fa-regular fa-comments']] as [$label,$value,$icon])<article class="article-stat"><i class="{{ $icon }}"></i><div><span>{{ $label }}</span><strong>{{ number_format($value) }}</strong></div></article>@endforeach</section>
    @php
      $maxViews = max(1, (int) $daily->max('views'));
    @endphp
    <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>روند ۱۰۰۰ رویداد اخیر</h2><p>ارتفاع ستون تعداد بازدید هر روز است؛ عدد کنار تاریخ مجموع همه تعامل‌هاست.</p></div></div><div class="article-chart">@forelse($daily as $date=>$point)<div class="article-chart__bar" title="{{ $point['views'] }} بازدید و {{ $point['events'] }} رویداد"><b>{{ $point['events'] }}</b><i style="height:{{ max(2,round(($point['views']/$maxViews)*170)) }}px"></i><small>{{ $date }}</small></div>@empty<div class="article-empty-admin"><i class="fa-solid fa-chart-line"></i><strong>هنوز داده‌ای ثبت نشده است.</strong></div>@endforelse</div></section>
    <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>شاخص‌های کیفیت</h2><p>برای تصمیم ویرایشی از نرخ‌ها در کنار موضوع و قدمت مقاله استفاده کنید.</p></div></div><div class="article-card-admin__body article-grid-3"><div class="article-stat"><i class="fa-solid fa-users-viewfinder"></i><div><span>نرخ بازدید یکتا</span><strong>{{ $article->view_count ? number_format(($article->unique_view_count/$article->view_count)*100,1) : 0 }}٪</strong></div></div><div class="article-stat"><i class="fa-solid fa-arrow-pointer"></i><div><span>نرخ کلیک محصول</span><strong>{{ $article->view_count ? number_format(($article->cta_click_count/$article->view_count)*100,1) : 0 }}٪</strong></div></div><div class="article-stat"><i class="fa-solid fa-share-nodes"></i><div><span>نرخ اشتراک</span><strong>{{ $article->view_count ? number_format(($article->share_count/$article->view_count)*100,1) : 0 }}٪</strong></div></div></div></section>
  </div></div>
</main>
@endsection
