@extends('layouts.admin')
@section('title', 'گزارش کلی مقالات — وطن استودیو')
@push('styles')<link rel="stylesheet" href="{{ asset('admin/css/articles.css') }}?v={{ filemtime(public_path('admin/css/articles.css')) }}">@endpush
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px] max-[480px]:p-[14px]" id="content" dir="rtl" style="background:var(--page-bg);"><div class="article-admin">
    <header class="article-page-head"><div class="article-page-head__copy"><small>تصویر کلی مرکز محتوا</small><h1>گزارش عملکرد مقالات</h1><p>داده‌های تجمیعی، مقالات برتر، رفتار ۳۰ روز اخیر و عملکرد دسته‌بندی‌ها.</p></div><a class="article-btn" href="{{ route('admin.articles.index') }}"><i class="fa-solid fa-arrow-right"></i> بازگشت به مقالات</a></header>
    <section class="article-stats">@foreach([['articles','کل مقالات','fa-regular fa-newspaper'],['published','منتشرشده','fa-solid fa-circle-check'],['views','بازدید کل','fa-regular fa-eye'],['unique_views','بازدید یکتا','fa-solid fa-user-check'],['shares','اشتراک‌گذاری','fa-solid fa-share-nodes'],['cta_clicks','کلیک محصول','fa-solid fa-arrow-pointer']] as [$key,$label,$icon])<article class="article-stat"><i class="{{ $icon }}"></i><div><span>{{ $label }}</span><strong>{{ number_format($totals[$key]) }}</strong></div></article>@endforeach</section>
    @php
      $maxViews = max(1, (int) $daily->max('views'));
    @endphp
    <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>روند رفتار کاربران در ۳۰ روز اخیر</h2><p>مجموع رویدادها و بازدید روزانه تا سقف ۲۰ هزار رویداد اخیر.</p></div></div><div class="article-chart">@forelse($daily as $date=>$point)<div class="article-chart__bar" title="{{ $point['views'] }} بازدید، {{ $point['events'] }} تعامل"><b>{{ $point['events'] }}</b><i style="height:{{ max(2,round(($point['views']/$maxViews)*170)) }}px"></i><small>{{ $date }}</small></div>@empty<div class="article-empty-admin"><i class="fa-solid fa-chart-line"></i><strong>هنوز داده‌ای برای این بازه وجود ندارد.</strong></div>@endforelse</div></section>
    <div class="article-grid-2">
      <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>مقالات پربازدید</h2><p>برای هر مقاله نرخ کلیک محصول نیز محاسبه شده است.</p></div></div><div class="article-table-wrap"><table class="article-table"><thead><tr><th>مقاله</th><th>بازدید</th><th>یکتا</th><th>کلیک</th><th>نرخ کلیک</th></tr></thead><tbody>@foreach($topArticles as $article)<tr><td><a href="{{ route('admin.articles.analytics',$article) }}"><strong>{{ str($article->title)->limit(45) }}</strong><br><small>{{ $article->category->name }}</small></a></td><td>{{ number_format($article->view_count) }}</td><td>{{ number_format($article->unique_view_count) }}</td><td>{{ number_format($article->cta_click_count) }}</td><td>{{ $article->view_count ? number_format(($article->cta_click_count/$article->view_count)*100,1) : 0 }}٪</td></tr>@endforeach</tbody></table></div></section>
      <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>عملکرد دسته‌بندی‌ها</h2><p>تعداد محتوا و مجموع بازدید هر شاخه.</p></div></div><div class="article-table-wrap"><table class="article-table"><thead><tr><th>دسته‌بندی</th><th>مقاله</th><th>بازدید</th></tr></thead><tbody>@foreach($categoryStats as $category)<tr><td>{{ $category->name }}</td><td>{{ number_format($category->articles_count) }}</td><td>{{ number_format($category->articles_sum_view_count ?? 0) }}</td></tr>@endforeach</tbody></table></div></section>
    </div>
    <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>تعامل‌های ۳۰ روز اخیر</h2><p>رویدادهای رفتاری بدون ذخیره نشانی اینترنتی خام کاربر ثبت می‌شوند.</p></div></div><div class="article-card-admin__body article-analytics-grid">@foreach(['view'=>'بازدید','scroll_50'=>'اسکرول ۵۰٪','scroll_90'=>'اسکرول ۹۰٪','toc_click'=>'کلیک فهرست','prompt_copy'=>'کپی پرامپت','product_cta_click'=>'کلیک محصول','share_click'=>'اشتراک‌گذاری','comment_submit'=>'ثبت دیدگاه'] as $event=>$label)<div class="article-stat"><i class="fa-solid fa-chart-simple"></i><div><span>{{ $label }}</span><strong>{{ number_format($eventCounts[$event] ?? 0) }}</strong></div></div>@endforeach</div></section>
  </div></div>
</main>
@endsection
