@extends('layouts.admin')
@section('title', 'دسته‌بندی مقالات — وطن استودیو')
@push('styles')<link rel="stylesheet" href="{{ asset('admin/css/articles.css') }}?v={{ filemtime(public_path('admin/css/articles.css')) }}">@endpush
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px] max-[480px]:p-[14px]" id="content" dir="rtl" style="background:var(--page-bg);"><div class="article-admin">
    <header class="article-page-head"><div class="article-page-head__copy"><small>ساختار موضوعی و سئو</small><h1>دسته‌بندی مقالات</h1><p>شاخه‌ها مستقل از دسته‌بندی محصولات هستند و صفحه آرشیو سئوشده دارند.</p></div><div class="article-page-actions"><a class="article-btn" href="{{ route('admin.articles.index') }}"><i class="fa-solid fa-arrow-right"></i> مقالات</a><a class="article-btn article-btn--primary" href="{{ route('admin.articles.create') }}"><i class="fa-solid fa-plus"></i> مقاله جدید</a></div></header>
    @include('admin.articles.partials.messages')
    <div class="article-categories-layout">
      <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>دسته جدید</h2><p>نامک و متای خالی به‌صورت خودکار تکمیل می‌شوند.</p></div></div><form class="article-card-admin__body article-admin" method="POST" action="{{ route('admin.article-categories.store') }}">@csrf
        <div class="article-field"><label>نام دسته</label><input class="article-input" name="name" required></div><div class="article-field"><label>نامک</label><input class="article-input" dir="ltr" name="slug" placeholder="auto-generated"></div><div class="article-field"><label>شاخه والد</label><select class="article-select" name="parent_id"><option value="">شاخه اصلی</option>@foreach($categories as $parent)<option value="{{ $parent->id }}">{{ $parent->name }}</option>@endforeach</select></div><div class="article-field"><label>توضیح دسته</label><textarea class="article-textarea" name="description"></textarea></div><div class="article-grid-2"><div class="article-field"><label>عنوان سئو</label><input class="article-input" name="meta_title"></div><div class="article-field"><label>اولویت</label><input class="article-input" type="number" min="0" name="sort_order" value="{{ $categories->max('sort_order')+1 }}"></div></div><div class="article-field"><label>توضیح سئو</label><textarea class="article-textarea" name="meta_description"></textarea></div><div class="article-switch-row"><label class="article-check"><input type="checkbox" name="is_active" value="1" checked> فعال</label><label class="article-check"><input type="checkbox" name="is_indexable" value="1" checked> قابل ایندکس</label></div><button class="article-btn article-btn--primary" type="submit">ثبت دسته‌بندی</button>
      </form></section>
      <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>شاخه‌های موجود</h2><p>{{ number_format($categories->count()) }} دسته‌بندی؛ دسته دارای مقاله یا زیرشاخه حذف نمی‌شود.</p></div></div><div>
        @foreach($categories as $category)<form class="article-category-row" method="POST" action="{{ route('admin.article-categories.update',$category) }}">@csrf @method('PUT')
          <div class="article-field"><label>نام</label><input class="article-input" name="name" value="{{ $category->name }}" required></div><div class="article-field"><label>نامک</label><input class="article-input" dir="ltr" name="slug" value="{{ $category->slug }}"></div><div class="article-field"><label>والد</label><select class="article-select" name="parent_id"><option value="">اصلی</option>@foreach($categories->where('id','!=',$category->id) as $parent)<option value="{{ $parent->id }}" @selected($category->parent_id===$parent->id)>{{ $parent->name }}</option>@endforeach</select></div><div class="article-field"><label>اولویت</label><input class="article-input" type="number" name="sort_order" value="{{ $category->sort_order }}"></div><div class="article-page-actions"><button class="article-btn article-btn--small" type="submit"><i class="fa-solid fa-floppy-disk"></i> ذخیره</button><button class="article-btn article-btn--danger article-btn--small" type="submit" form="delete-category-{{ $category->id }}" onclick="return confirm('این دسته حذف شود؟')"><i class="fa-solid fa-trash"></i></button></div>
          <div class="article-field" style="grid-column:1/-1;"><label>توضیح</label><input class="article-input" name="description" value="{{ $category->description }}"></div><div class="article-field" style="grid-column:1/3;"><label>عنوان سئو</label><input class="article-input" name="meta_title" value="{{ $category->meta_title }}"></div><div class="article-field" style="grid-column:3/5;"><label>توضیح سئو</label><input class="article-input" name="meta_description" value="{{ $category->meta_description }}"></div><div class="article-switch-row"><label class="article-check"><input type="checkbox" name="is_active" value="1" @checked($category->is_active)> فعال</label><label class="article-check"><input type="checkbox" name="is_indexable" value="1" @checked($category->is_indexable)> ایندکس</label><span class="article-status">{{ $category->articles_count }} مقاله</span></div>
        </form>@endforeach
      </div></section>
    </div>
    @foreach($categories as $category)<form id="delete-category-{{ $category->id }}" method="POST" action="{{ route('admin.article-categories.destroy',$category) }}">@csrf @method('DELETE')</form>@endforeach
  </div></div>
</main>
@endsection
