@extends('layouts.admin')
@section('title', 'مدیریت دیدگاه مقالات — وطن استودیو')
@push('styles')<link rel="stylesheet" href="{{ asset('admin/css/articles.css') }}?v={{ filemtime(public_path('admin/css/articles.css')) }}">@endpush
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px] max-[480px]:p-[14px]" id="content" dir="rtl" style="background:var(--page-bg);"><div class="article-admin">
    <header class="article-page-head"><div class="article-page-head__copy"><small>نظارت و گفت‌وگو</small><h1>دیدگاه مقالات</h1><p>همه دیدگاه‌ها پیش از نمایش عمومی نیازمند تأیید هستند.</p></div><a class="article-btn" href="{{ route('admin.articles.index') }}"><i class="fa-solid fa-arrow-right"></i> مقالات</a></header>
    @include('admin.articles.partials.messages')
    <section class="article-stats">@foreach(['pending'=>'منتظر بررسی','approved'=>'تأییدشده','rejected'=>'ردشده','spam'=>'هرزنامه'] as $status=>$label)<a class="article-stat" href="{{ route('admin.article-comments.index',['status'=>$status]) }}"><i class="fa-regular fa-comment-dots"></i><div><span>{{ $label }}</span><strong>{{ number_format($counts[$status] ?? 0) }}</strong></div></a>@endforeach</section>
    <section class="article-card-admin"><div class="article-card-admin__head"><div><h2>صف بررسی دیدگاه‌ها</h2><p>متن، نویسنده و مقاله مقصد را پیش از تصمیم ببینید.</p></div><form method="GET" action="{{ route('admin.article-comments.index') }}" class="article-page-actions"><input class="article-input" name="search" value="{{ request('search') }}" placeholder="جست‌وجو در دیدگاه یا مقاله"><select class="article-select" name="status"><option value="">همه</option>@foreach(['pending'=>'منتظر','approved'=>'تأیید','rejected'=>'ردشده','spam'=>'هرزنامه'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="article-btn" type="submit">فیلتر</button></form></div><div class="article-card-admin__body article-comment-list">
      @forelse($comments as $comment)<article class="article-comment-row"><div><div class="article-comment-row__meta"><strong>{{ trim(($comment->user?->name ?? 'کاربر حذف‌شده').' '.($comment->user?->last_name ?? '')) }}</strong><span>{{ $comment->created_at->diffForHumans() }}</span><a href="{{ $comment->article?->publicUrl() }}?preview=1" target="_blank">{{ $comment->article?->title }}</a><span class="article-status article-status--{{ $comment->status }}">{{ ['pending'=>'منتظر','approved'=>'تأییدشده','rejected'=>'ردشده','spam'=>'هرزنامه'][$comment->status] ?? $comment->status }}</span></div><p>{{ $comment->body }}</p></div><div class="article-comment-row__actions"><form method="POST" action="{{ route('admin.article-comments.update',$comment) }}">@csrf @method('PATCH')<select class="article-select" name="status">@foreach(['pending'=>'منتظر بررسی','approved'=>'تأیید و نمایش','rejected'=>'رد دیدگاه','spam'=>'هرزنامه'] as $value=>$label)<option value="{{ $value }}" @selected($comment->status===$value)>{{ $label }}</option>@endforeach</select><button class="article-btn" type="submit">ثبت وضعیت</button></form><form method="POST" action="{{ route('admin.article-comments.destroy',$comment) }}" onsubmit="return confirm('این دیدگاه حذف شود؟')">@csrf @method('DELETE')<button class="article-btn article-btn--danger" type="submit">حذف</button></form></div></article>@empty<div class="article-empty-admin"><i class="fa-regular fa-comments"></i><strong>دیدگاهی برای بررسی وجود ندارد.</strong></div>@endforelse
    </div><div class="article-pagination">{{ $comments->links() }}</div></section>
  </div></div>
</main>
@endsection
