<section class="article-card-admin">
  <div class="article-card-admin__head"><div><h2>انتشار و دسترسی</h2><p>تصمیم انتشار نهایی فقط در اختیار مدیر ارشد است.</p></div></div>
  <div class="article-card-admin__body article-admin">
    <div class="article-field"><label for="article-publish-status">وضعیت</label><select class="article-select" id="article-publish-status" name="status" required data-publish-status>@foreach(['draft'=>'پیش‌نویس','in_review'=>'ارسال برای بررسی','changes_requested'=>'نیازمند اصلاح','scheduled'=>'زمان‌بندی انتشار','published'=>'منتشرشده','archived'=>'آرشیوشده'] as $value=>$label)@if(auth('admin')->user()?->isLeader() || !in_array($value,['scheduled','published'],true) || $article->status===$value)<option value="{{ $value }}" @selected(old('status',$article->status ?: 'draft')===$value)>{{ $label }}</option>@endif @endforeach</select></div>
    <div class="article-field" data-schedule-field><label for="article-scheduled-at">زمان انتشار برنامه‌ریزی‌شده</label><input class="article-input" id="article-scheduled-at" type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at',$article->scheduled_at?->format('Y-m-d\TH:i')) }}"></div>
    <div class="article-field"><label for="article-published-at">تاریخ انتشار</label><input class="article-input" id="article-published-at" type="datetime-local" name="published_at" value="{{ old('published_at',$article->published_at?->format('Y-m-d\TH:i')) }}"><small>در انتشار جدید، اگر خالی باشد زمان جاری ثبت می‌شود.</small></div>
    <div class="article-field"><label for="article-reviewer">بازبین محتوا</label><select class="article-select" id="article-reviewer" name="reviewer_id"><option value="">بدون بازبین مشخص</option>@foreach($admins as $admin)<option value="{{ $admin->id }}" @selected((int)old('reviewer_id',$article->reviewer_id)===$admin->id)>{{ $admin->name }} — {{ $admin->role === 'leader' ? 'مدیر ارشد' : 'مدیر' }}</option>@endforeach</select></div>
    <div class="article-switch-row"><label class="article-check"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$article->exists ? $article->is_featured : false))> مقاله منتخب</label><label class="article-check"><input type="checkbox" name="allow_comments" value="1" @checked(old('allow_comments',$article->exists ? $article->allow_comments : true))> دیدگاه فعال</label></div>
    <div class="article-field"><label for="article-change-note">یادداشت این نسخه</label><input class="article-input" id="article-change-note" name="change_note" value="{{ old('change_note') }}" maxlength="255" placeholder="مثلاً بروزرسانی بخش پرامپت‌ها"></div>
    <button class="article-btn article-btn--primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> {{ $article->exists ? 'ذخیره تغییرات' : 'ثبت مقاله' }}</button>
  </div>
</section>
@if($article->exists)
<section class="article-card-admin"><div class="article-card-admin__head"><div><h2>عملیات مقاله</h2><p>حذف نرم قابل بازیابی است.</p></div></div><div class="article-card-admin__body article-page-actions">@if($article->status!=='archived')<button class="article-btn" type="submit" form="article-archive-form"><i class="fa-solid fa-box-archive"></i> آرشیو</button>@endif<button class="article-btn article-btn--danger" type="submit" form="article-delete-form"><i class="fa-regular fa-trash-can"></i> انتقال به زباله‌دان</button></div></section>
@endif
