<form method="POST" action="{{ route('admin.articles.bulk') }}">@csrf
  <div class="article-table-wrap">
    <table class="article-table"><thead><tr><th><input type="checkbox" data-article-check-all aria-label="انتخاب همه"></th><th>مقاله</th><th>وضعیت</th><th>دسته و نویسنده</th><th>عملکرد</th><th>بروزرسانی</th><th>عملیات</th></tr></thead><tbody>
      @forelse($articles as $article)
        <tr><td><input type="checkbox" name="article_ids[]" value="{{ $article->id }}" data-article-check></td><td><div class="article-table__title">@if($article->imageUrl())<img src="{{ $article->imageUrl() }}" alt="">@else<span class="article-table__placeholder"><i class="fa-regular fa-image"></i></span>@endif<div><strong>{{ $article->title }}</strong><small>/articles/{{ $article->slug }} · {{ $article->contentTypeLabel() }}</small></div></div></td><td><span class="article-status article-status--{{ $article->status }}">{{ $article->statusLabel() }}</span></td><td><strong>{{ $article->category->name }}</strong><br><small>{{ $article->author->name }}</small></td><td><i class="fa-regular fa-eye"></i> {{ number_format($article->view_count) }} &nbsp; <i class="fa-regular fa-comment"></i> {{ number_format($article->comments_count) }}</td><td>{{ $article->updated_at->diffForHumans() }}</td><td><div class="article-table__actions">@if($article->trashed())<button class="article-icon-btn" type="submit" form="restore-article-{{ $article->id }}" title="بازیابی"><i class="fa-solid fa-rotate-left"></i></button>@if(auth('admin')->user()?->isLeader())<button class="article-icon-btn" type="submit" form="force-delete-article-{{ $article->id }}" onclick="return confirm('این مقاله برای همیشه حذف شود؟')" title="حذف دائمی"><i class="fa-solid fa-trash"></i></button>@endif @else<a class="article-icon-btn" href="{{ route('admin.articles.edit',$article) }}" title="ویرایش"><i class="fa-regular fa-pen-to-square"></i></a><a class="article-icon-btn" href="{{ route('admin.articles.analytics',$article) }}" title="گزارش"><i class="fa-solid fa-chart-line"></i></a><a class="article-icon-btn" href="{{ $article->publicUrl() }}?preview=1" target="_blank" title="پیش‌نمایش"><i class="fa-solid fa-arrow-up-right-from-square"></i></a>@endif</div></td></tr>
      @empty<tr><td colspan="7"><div class="article-empty-admin"><i class="fa-regular fa-folder-open"></i><strong>مقاله‌ای با این فیلتر پیدا نشد.</strong></div></td></tr>@endforelse
    </tbody></table>
  </div>
  @if($articles->isNotEmpty() && request('status') !== 'trash')<div class="article-bulk"><select class="article-select" name="action" required><option value="">عملیات گروهی...</option>@if(auth('admin')->user()?->isLeader())<option value="publish">انتشار</option>@endif<option value="archive">آرشیو</option><option value="delete">انتقال به زباله‌دان</option></select><button class="article-btn" type="submit">اجرا روی انتخاب‌ها</button></div>@endif
</form>
@foreach($articles as $article)@if($article->trashed())<form id="restore-article-{{ $article->id }}" method="POST" action="{{ route('admin.articles.restore',$article->id) }}">@csrf @method('PATCH')</form>@if(auth('admin')->user()?->isLeader())<form id="force-delete-article-{{ $article->id }}" method="POST" action="{{ route('admin.articles.force-delete',$article->id) }}">@csrf @method('DELETE')</form>@endif @endif @endforeach
<div class="article-pagination">{{ $articles->links() }}</div>
<script>document.querySelector('[data-article-check-all]')?.addEventListener('change',function(){document.querySelectorAll('[data-article-check]').forEach((item)=>item.checked=this.checked)})</script>
