@extends('layouts.admin')

@section('title', 'تقویم و صف محتوا — تکنولوژی مارکتینگ')

@push('styles')
<link href="{{ asset('admin/css/marketing-technology.css') }}?v={{ filemtime(public_path('admin/css/marketing-technology.css')) }}" rel="stylesheet">
@endpush

@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="marketing-tech-page admin-content flex-1 overflow-y-auto" id="content">
    @if(session('success'))<div class="mt-alert mt-alert-success"><i class="fa-solid fa-circle-check"></i>{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mt-alert mt-alert-danger"><i class="fa-solid fa-circle-exclamation"></i><span>@foreach($errors->all() as $error){{ $error }}@if(!$loop->last)، @endif @endforeach</span></div>@endif
    <div class="mt-page-head"><div><div class="mt-eyebrow">تکنولوژی مارکتینگ</div><h1>تقویم و صف محتوا</h1><p>برنامه‌ریزی سه پست روزانه، اتصال به محصول و سناریو، و ورود کنترل‌شده به صف عملیات.</p></div><div class="mt-head-actions"><span class="mt-status"><span></span>{{ $ready ? 'داده‌محور' : 'در انتظار مهاجرت' }}</span><a class="mt-btn" href="{{ route('admin.marketing-technology.index') }}"><i class="fa-solid fa-arrow-right"></i> مرکز فرماندهی</a></div></div>

    @if(!$ready)
      <section class="mt-card mt-empty-section"><span class="mt-empty-icon"><i class="fa-solid fa-database"></i></span><h2>مدل داده هنوز روی این محیط اجرا نشده است</h2><p>پس از اجرای مهاجرت فاز دو، فرم تقویم و صف عملیات فعال می‌شود.</p><span class="mt-badge mt-badge-warn">در انتظار استقرار</span></section>
    @else
      <section class="mt-kpis mt-calendar-kpis"><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>کل محتواها</span><i class="fa-solid fa-photo-film"></i></div><strong>{{ number_format($contents->total()) }}</strong><small>در تقویم مستقل</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>آماده‌ی اجرا</span><i class="fa-solid fa-list-check"></i></div><strong>{{ number_format($contents->getCollection()->whereIn('status', ['ready', 'scheduled'])->count()) }}</strong><small>در صفحه‌ی جاری</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>صف عملیات</span><i class="fa-solid fa-layer-group"></i></div><strong>{{ number_format($operations->where('status', 'queued')->count()) }}</strong><small>منتظر اجرای کنترل‌شده</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>سناریوهای فعال</span><i class="fa-solid fa-comments"></i></div><strong>{{ number_format($scenarios->where('status', 'active')->count()) }}</strong><small>قابل انتخاب برای محتوا</small></article></section>

      <section class="mt-grid mt-calendar-grid">
        <article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>ثبت محتوای جدید</h2><p>اطلاعات پایه را ثبت کن؛ اتصال تولید و انتشار در مرحله‌ی بعدی به آن اضافه می‌شود.</p></div><span class="mt-badge">فاز سه</span></div><form method="POST" action="{{ route('admin.marketing-technology.content-calendar.store') }}" class="mt-form-grid">@csrf<div class="mt-field mt-field-wide"><label>عنوان محتوا</label><input class="mt-input" name="title" required placeholder="مثلاً ریلز پورتره مردانه"></div><div class="mt-field"><label>محصول</label><select class="mt-input" name="product_id"><option value="">انتخاب محصول</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name_fa }}{{ $product->product_code ? ' — '.$product->product_code : '' }}</option>@endforeach</select></div><div class="mt-field"><label>کمپین</label><select class="mt-input" name="marketing_campaign_id"><option value="">بدون کمپین</option>@foreach($campaigns as $campaign)<option value="{{ $campaign->id }}">{{ $campaign->name }}</option>@endforeach</select></div><div class="mt-field"><label>سناریو</label><select class="mt-input" name="marketing_scenario_id"><option value="">بدون سناریو</option>@foreach($scenarios as $scenario)<option value="{{ $scenario->id }}">{{ $scenario->name }}</option>@endforeach</select></div><div class="mt-field"><label>نوع محتوا</label><select class="mt-input" name="content_type"><option value="reel">ریلز</option><option value="post">پست</option><option value="story">استوری</option><option value="video">ویدیو</option></select></div><div class="mt-field"><label>وضعیت اولیه</label><select class="mt-input" name="status"><option value="draft">پیش‌نویس</option><option value="scheduled">زمان‌بندی‌شده</option><option value="ready">آماده اجرا</option><option value="paused">متوقف</option></select></div><div class="mt-field"><label>زمان انتشار</label><input class="mt-input" type="datetime-local" name="publish_at"></div><div class="mt-field"><label>کلمه‌ی کلیدی</label><input class="mt-input" name="keyword" placeholder="مثلاً پورتره"></div><div class="mt-field mt-field-wide"><label>هوک</label><input class="mt-input" name="hook" placeholder="هوک پیشنهادی یا نهایی"></div><div class="mt-field mt-field-wide"><label>کپشن</label><textarea class="mt-input mt-textarea" name="caption" placeholder="متن کپشن را وارد کن..."></textarea></div><div class="mt-form-actions"><button class="mt-btn mt-btn-primary" type="submit"><i class="fa-solid fa-plus"></i> افزودن به تقویم</button></div></form></article>

        <article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>آخرین اجرای عملیات</h2><p>وضعیت آماده‌سازی محتوا قبل از اتصال به `n8n`.</p></div><a class="mt-btn" href="{{ route('admin.marketing-technology.logs') }}">مشاهده لاگ</a></div>@if($operations->isEmpty())<div class="mt-note">هنوز عملیاتی وارد صف نشده است.</div>@else<div class="mt-operation-list">@foreach($operations as $operation)<div class="mt-operation"><span class="mt-operation-icon"><i class="fa-solid {{ $operation->status === 'completed' ? 'fa-check' : ($operation->status === 'failed' ? 'fa-xmark' : 'fa-clock') }}"></i></span><div><strong>{{ $operation->content?->title ?? 'عملیات بدون محتوا' }}</strong><small>{{ $operation->operation_type }} · تلاش {{ $operation->attempt }}</small></div><span class="mt-badge {{ $operation->status === 'failed' ? 'mt-badge-danger' : ($operation->status === 'completed' ? 'mt-badge-success' : '') }}">{{ ['queued' => 'در صف', 'running' => 'در حال اجرا', 'completed' => 'تکمیل‌شده', 'failed' => 'ناموفق', 'cancelled' => 'لغوشده'][$operation->status] ?? $operation->status }}</span></div>@endforeach</div>@endif</article>
      </section>

      <section class="mt-card mt-card-pad mt-table-card"><div class="mt-section-head"><div><h2>تقویم محتوا</h2><p>هر ردیف بعداً به شناسه‌ی کمپین، لینک و آمار `Instagram` متصل خواهد شد.</p></div><form method="GET" class="mt-filter-form"><select class="mt-input mt-input-compact" name="status"><option value="">همه وضعیت‌ها</option><option value="draft" @selected(request('status') === 'draft')>پیش‌نویس</option><option value="scheduled" @selected(request('status') === 'scheduled')>زمان‌بندی‌شده</option><option value="ready" @selected(request('status') === 'ready')>آماده اجرا</option><option value="paused" @selected(request('status') === 'paused')>متوقف</option></select><button class="mt-btn" type="submit">فیلتر</button></form></div><div class="mt-table-wrap"><table class="mt-table"><thead><tr><th>محتوا</th><th>محصول</th><th>زمان انتشار</th><th>سناریو</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>@forelse($contents as $content)<tr><td><strong>{{ $content->title }}</strong><small>{{ $content->content_type }}{{ $content->keyword ? ' · '.$content->keyword : '' }}</small></td><td>{{ $content->product?->name_fa ?? '—' }}</td><td>{{ $content->publish_at?->format('Y/m/d H:i') ?? 'بدون زمان' }}</td><td>{{ $content->scenario?->name ?? '—' }}</td><td><span class="mt-badge {{ in_array($content->status, ['ready', 'published']) ? 'mt-badge-success' : ($content->status === 'paused' ? 'mt-badge-danger' : 'mt-badge-warn') }}">{{ ['draft' => 'پیش‌نویس', 'scheduled' => 'زمان‌بندی‌شده', 'ready' => 'آماده اجرا', 'published' => 'منتشرشده', 'paused' => 'متوقف'][$content->status] ?? $content->status }}</span></td><td><form method="POST" action="{{ route('admin.marketing-technology.content-calendar.queue', $content) }}">@csrf<button class="mt-btn mt-btn-small" type="submit" {{ in_array($content->status, ['paused', 'published']) ? 'disabled' : '' }}><i class="fa-solid fa-list-check"></i> ورود به صف</button></form></td></tr>@empty<tr><td colspan="6"><div class="mt-table-empty"><i class="fa-solid fa-calendar-xmark"></i><strong>محتوایی ثبت نشده است</strong><small>از فرم بالا اولین محتوای تقویم را بساز.</small></div></td></tr>@endforelse</tbody></table></div><div class="mt-pagination">{{ $contents->links() }}</div></section>
    @endif
  </div>
</main>
@endsection
