@extends('layouts.admin')

@section('title', 'مرکز هزینه — تکنولوژی مارکتینگ')

@push('styles')
<link href="{{ asset('admin/css/marketing-technology.css') }}?v={{ filemtime(public_path('admin/css/marketing-technology.css')) }}" rel="stylesheet">
@endpush

@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="marketing-tech-page admin-content flex-1 overflow-y-auto" id="content">
    @if(session('success'))<div class="mt-alert mt-alert-success"><i class="fa-solid fa-circle-check"></i>{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mt-alert mt-alert-danger"><i class="fa-solid fa-circle-exclamation"></i><span>@foreach($errors->all() as $error){{ $error }}@if(!$loop->last)، @endif @endforeach</span></div>@endif
    <div class="mt-page-head"><div><div class="mt-eyebrow">تکنولوژی مارکتینگ</div><h1>مرکز هزینه</h1><p>هزینه‌ی هر عملیات، محتوا و کمپین را با نرخ ارز ثبت‌شده و قابل ردیابی بررسی کن.</p></div><div class="mt-head-actions"><span class="mt-status"><span></span> دفتر هزینه داخلی</span><a class="mt-btn" href="{{ route('admin.marketing-technology.index') }}"><i class="fa-solid fa-arrow-right"></i> مرکز فرماندهی</a></div></div>
    <form method="GET" class="mt-card mt-card-pad mt-report-filters"><div class="mt-field"><label>از تاریخ</label><input class="mt-input" type="date" name="from" value="{{ $range['from']->format('Y-m-d') }}"></div><div class="mt-field"><label>تا تاریخ</label><input class="mt-input" type="date" name="to" value="{{ $range['to']->format('Y-m-d') }}"></div><div class="mt-form-actions"><button class="mt-btn mt-btn-primary" type="submit"><i class="fa-solid fa-filter"></i> اعمال فیلتر</button></div></form>
    <section class="mt-kpis mt-report-kpis"><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>کل هزینه</span><i class="fa-solid fa-coins"></i></div><strong class="mt-money">{{ number_format($metrics['total']) }}</strong><small>تومان در بازه</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>هزینه‌ی معتبر</span><i class="fa-solid fa-circle-check"></i></div><strong class="mt-money">{{ number_format($metrics['known']) }}</strong><small>قابل استفاده در گزارش سود</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>نیازمند بررسی</span><i class="fa-solid fa-triangle-exclamation"></i></div><strong>{{ number_format($metrics['pending']) }}</strong><small>رویداد بدون مبلغ قطعی</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>تعداد رویداد</span><i class="fa-solid fa-receipt"></i></div><strong>{{ number_format($metrics['events']) }}</strong><small>میانگین {{ number_format($metrics['average']) }} تومان</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>نرخ دلار ثبت‌شده</span><i class="fa-solid fa-dollar-sign"></i></div><strong class="mt-money">{{ $rate['value'] > 0 ? number_format($rate['value']) : '—' }}</strong><small>{{ $rate['source'] }}{{ $rate['date'] ? ' · '.$rate['date'] : '' }}</small></article></section>
    <section class="mt-grid mt-cost-grid"><article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>ثبت هزینه</h2><p>برای هزینه‌های دستی یا سرویس‌هایی که هنوز اتصال خودکار ندارند.</p></div><span class="mt-badge">قابل ردیابی</span></div><form method="POST" action="{{ route('admin.marketing-technology.costs.store') }}" class="mt-form-grid">@csrf<div class="mt-field"><label>ارائه‌دهنده</label><input class="mt-input" name="provider" required placeholder="مثلاً OpenRouter"></div><div class="mt-field"><label>سرویس</label><input class="mt-input" name="service" required placeholder="مثلاً تولید کپشن"></div><div class="mt-field"><label>تعداد واحد</label><input class="mt-input" name="units" type="number" min="0" step="0.000001" required value="1"></div><div class="mt-field"><label>واحد</label><input class="mt-input" name="unit" placeholder="تعداد، ثانیه، توکن..."></div><div class="mt-field"><label>قیمت هر واحد به دلار</label><input class="mt-input" name="unit_cost_usd" type="number" min="0" step="0.00000001"></div><div class="mt-field"><label>نرخ دلار به تومان</label><input class="mt-input" name="fx_rate_toman" type="number" min="0" step="0.01" value="{{ $rate['value'] > 0 ? $rate['value'] : '' }}"></div><div class="mt-field"><label>هزینه قطعی به تومان</label><input class="mt-input" name="cost_toman" type="number" min="0" placeholder="اختیاری؛ در غیر این صورت محاسبه می‌شود"></div><div class="mt-field"><label>وضعیت</label><select class="mt-input" name="status"><option value="estimated">تخمینی</option><option value="actual">قطعی</option><option value="needs_review">نیازمند بررسی</option></select></div><div class="mt-field"><label>کمپین</label><select class="mt-input" name="marketing_campaign_id"><option value="">بدون کمپین</option>@foreach($campaigns as $campaign)<option value="{{ $campaign->id }}">{{ $campaign->name }}</option>@endforeach</select></div><div class="mt-field"><label>محتوا</label><select class="mt-input" name="marketing_content_id"><option value="">بدون محتوا</option>@foreach($contents as $content)<option value="{{ $content->id }}">{{ $content->title }}</option>@endforeach</select></div><div class="mt-field"><label>زمان مصرف</label><input class="mt-input" type="datetime-local" name="incurred_at" required value="{{ now()->format('Y-m-d\TH:i') }}"></div><div class="mt-form-actions"><button class="mt-btn mt-btn-primary" type="submit"><i class="fa-solid fa-plus"></i> ثبت رویداد هزینه</button></div></form></article><article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>روند هزینه</h2><p>هزینه‌ی ثبت‌شده به تفکیک روز</p></div></div><div class="mt-chart-box"><canvas id="marketingCostChart" data-labels='@json($daily['labels'])' data-costs='@json($daily['costs'])'></canvas></div><div class="mt-note mt-cost-formula"><strong>فرمول محاسبه</strong><span>واحد مصرف × قیمت دلاری × نرخ دلار = هزینه‌ی تومانی</span></div></article></section>
    <section class="mt-grid mt-cost-bottom"><article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>هزینه به تفکیک سرویس</h2><p>مقایسه‌ی ارائه‌دهندگان در بازه</p></div></div>@if($providers->isEmpty())<div class="mt-table-empty"><i class="fa-solid fa-coins"></i><strong>هنوز هزینه‌ای ثبت نشده است</strong></div>@else<div class="mt-table-wrap"><table class="mt-table"><thead><tr><th>ارائه‌دهنده</th><th>رویداد</th><th>هزینه</th><th>معتبر</th></tr></thead><tbody>@foreach($providers as $provider)<tr><td><strong>{{ $provider['label'] }}</strong></td><td>{{ number_format($provider['events']) }}</td><td>{{ number_format($provider['cost']) }} تومان</td><td>{{ number_format($provider['known']) }}</td></tr>@endforeach</tbody></table></div>@endif</article><article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>آخرین هزینه‌ها</h2><p>ردیابی عملیاتی برای بررسی و اصلاح</p></div></div>@if($recentCosts->isEmpty())<div class="mt-table-empty"><i class="fa-solid fa-receipt"></i><strong>رویدادی ثبت نشده است</strong></div>@else<div class="mt-operation-list">@foreach($recentCosts as $cost)<div class="mt-operation"><span class="mt-operation-icon"><i class="fa-solid fa-receipt"></i></span><div><strong>{{ $cost->provider }} — {{ $cost->service }}</strong><small>{{ number_format((float) $cost->units, 2) }} {{ $cost->unit ?? 'واحد' }} · {{ $cost->incurred_at?->format('Y/m/d H:i') }}</small></div><span class="mt-badge {{ $cost->status === 'needs_review' ? 'mt-badge-warn' : 'mt-badge-success' }}">{{ $cost->status === 'actual' ? 'قطعی' : ($cost->status === 'estimated' ? 'تخمینی' : 'بررسی') }}</span></div>@endforeach</div>@endif</article></section>
  </div>
</main>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>(function(){if(typeof Chart==='undefined')return;const c=document.getElementById('marketingCostChart');if(!c)return;const v=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();new Chart(c,{type:'bar',data:{labels:JSON.parse(c.dataset.labels),datasets:[{label:'هزینه تومان',data:JSON.parse(c.dataset.costs),backgroundColor:v('--primary'),borderRadius:8,maxBarThickness:30}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{rtl:true,bodyFont:{family:'YekanBakh'}}},scales:{x:{grid:{display:false},ticks:{color:v('--text-soft'),font:{family:'YekanBakh',size:9}}},y:{beginAtZero:true,grid:{color:v('--divider')},ticks:{color:v('--text-soft'),font:{family:'YekanBakh',size:9}}}}}});})();</script>
@endsection
