@extends('layouts.admin')

@section('title', 'صندوق گفتگوها — تکنولوژی مارکتینگ')

@push('styles')
<link href="{{ asset('admin/css/marketing-technology.css') }}?v={{ filemtime(public_path('admin/css/marketing-technology.css')) }}" rel="stylesheet">
@endpush

@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="marketing-tech-page admin-content flex-1 overflow-y-auto" id="content">
    <div class="mt-page-head"><div><div class="mt-eyebrow">تکنولوژی مارکتینگ</div><h1>صندوق گفتگوها</h1><p>کامنت‌ها و دایرکت‌های دریافتی را با سناریو، محتوا و وضعیت پردازش دنبال کن.</p></div><div class="mt-head-actions"><span class="mt-status"><span></span> رویدادهای ورودی</span><a class="mt-btn" href="{{ route('admin.marketing-technology.index') }}"><i class="fa-solid fa-arrow-right"></i> مرکز فرماندهی</a></div></div>
    <form method="GET" class="mt-card mt-card-pad mt-log-filter"><div class="mt-field"><label>جست‌وجو</label><input class="mt-input" name="search" value="{{ request('search') }}" placeholder="شناسه یا نوع رویداد"></div><div class="mt-field"><label>کانال</label><select class="mt-input" name="channel"><option value="">همه کانال‌ها</option><option value="instagram" @selected(request('channel') === 'instagram')>اینستاگرام</option><option value="telegram" @selected(request('channel') === 'telegram')>تلگرام</option></select></div><div class="mt-field"><label>پردازش</label><select class="mt-input" name="processing_status"><option value="">همه وضعیت‌ها</option><option value="received" @selected(request('processing_status') === 'received')>دریافت‌شده</option><option value="processed" @selected(request('processing_status') === 'processed')>پردازش‌شده</option><option value="failed" @selected(request('processing_status') === 'failed')>ناموفق</option></select></div><div class="mt-form-actions"><button class="mt-btn mt-btn-primary" type="submit"><i class="fa-solid fa-filter"></i> اعمال فیلتر</button></div></form>
    <section class="mt-card mt-card-pad mt-table-card"><div class="mt-section-head"><div><h2>رویدادهای گفتگو</h2><p>رویداد خام حفظ می‌شود تا پاسخ و تحلیل بعدی قابل ردیابی باشد.</p></div><span class="mt-badge">{{ number_format($events->total()) }} رویداد</span></div>@if(!$ready)<div class="mt-note">مدل رویداد هنوز روی این محیط اجرا نشده است.</div>@elseif($events->isEmpty())<div class="mt-table-empty"><i class="fa-solid fa-inbox"></i><strong>هنوز گفت‌وگویی دریافت نشده است</strong><small>پس از اتصال وب‌هوک `Meta` رویدادها اینجا نمایش داده می‌شوند.</small></div>@else<div class="mt-table-wrap"><table class="mt-table"><thead><tr><th>نوع رویداد</th><th>کانال</th><th>محتوا / سناریو</th><th>شناسه بیرونی</th><th>پردازش</th><th>زمان</th></tr></thead><tbody>@foreach($events as $event)@php($eventLabels = ['comment.received' => 'کامنت دریافتی', 'dm.received' => 'دایرکت دریافتی', 'message.received' => 'پیام دریافتی', 'link.clicked' => 'کلیک لینک', 'link.opened' => 'بازشدن مقصد'])<tr><td><span class="mt-event-type">{{ $eventLabels[$event->event_type] ?? $event->event_type }}</span></td><td>{{ ['instagram' => 'اینستاگرام', 'telegram' => 'تلگرام', 'youtube' => 'یوتیوب'][$event->channel] ?? ($event->channel ?: '—') }}</td><td><strong>{{ $event->content?->title ?? 'بدون محتوا' }}</strong><small>{{ $event->scenario?->name ?? 'بدون سناریو' }}</small></td><td><span class="mt-event-meta">{{ $event->external_id ?: '—' }}</span></td><td><span class="mt-log-status mt-log-status-{{ $event->processing_status }}">{{ ['received' => 'دریافت‌شده', 'processed' => 'پردازش‌شده', 'failed' => 'ناموفق'][$event->processing_status] ?? $event->processing_status }}</span></td><td>{{ $event->occurred_at?->format('Y/m/d H:i') }}</td></tr>@endforeach</tbody></table></div><div class="mt-pagination">{{ $events->links() }}</div>@endif</section>
  </div>
</main>
@endsection
