@extends('layouts.admin')

@section('title', 'گزارش و تحلیل — تکنولوژی مارکتینگ')

@push('styles')
<link href="{{ asset('admin/css/marketing-technology.css') }}?v={{ filemtime(public_path('admin/css/marketing-technology.css')) }}" rel="stylesheet">
@endpush

@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="marketing-tech-page admin-content flex-1 overflow-y-auto" id="content">
    <div class="mt-page-head"><div><div class="mt-eyebrow">تکنولوژی مارکتینگ</div><h1>گزارش و تحلیل</h1><p>عملکرد محتوا، کانال، سناریو و مسیر تبدیل را در یک نمای قابل تصمیم‌گیری ببین.</p></div><div class="mt-head-actions"><span class="mt-status"><span></span> گزارش داخلی</span><a class="mt-btn" href="{{ route('admin.marketing-technology.index') }}"><i class="fa-solid fa-arrow-right"></i> مرکز فرماندهی</a></div></div>
    <section class="mt-card mt-report-note"><div><strong><i class="fa-solid fa-wand-magic-sparkles"></i> بینش خودکار</strong><p>{{ $metrics['clicks'] === 0 ? 'برای تولید بینش، اولین کلیک یا رویداد اجتماعی باید وارد سیستم شود.' : ($metrics['open_rate'] < 50 ? 'بخش قابل توجهی از کلیک‌ها به بازشدن مقصد نرسیده است؛ لینک و سرعت مقصد بررسی شود.' : 'مسیر کلیک تا بازشدن مقصد در این بازه پایدار است؛ تمرکز بعدی روی ساخت و خرید قرار می‌گیرد.') }}</p></div><span class="mt-badge">بدون اجرای خودکار</span></section>
    @if(!$dataStatus['social'])<div class="mt-alert mt-alert-info"><i class="fa-solid fa-circle-info"></i><span>{{ $dataStatus['message'] }} آمار شبکه‌های اجتماعی پس از اتصال منبع رسمی اضافه می‌شود.</span></div>@endif
    <form method="GET" class="mt-card mt-card-pad mt-report-filters"><div class="mt-field"><label>از تاریخ</label><input class="mt-input" type="date" name="from" value="{{ $range['from']->format('Y-m-d') }}"></div><div class="mt-field"><label>تا تاریخ</label><input class="mt-input" type="date" name="to" value="{{ $range['to']->format('Y-m-d') }}"></div><div class="mt-field"><label>کانال</label><select class="mt-input" name="channel"><option value="">همه کانال‌ها</option><option value="instagram" @selected(request('channel') === 'instagram')>اینستاگرام</option><option value="telegram" @selected(request('channel') === 'telegram')>تلگرام</option><option value="youtube" @selected(request('channel') === 'youtube')>یوتیوب</option></select></div><div class="mt-form-actions"><button class="mt-btn mt-btn-primary" type="submit"><i class="fa-solid fa-filter"></i> اعمال فیلتر</button></div></form>
    <section class="mt-kpis mt-report-kpis"><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>نمایش محتوا</span><i class="fa-solid fa-eye"></i></div><strong>{{ number_format($metrics['views']) }}</strong><small>در بازه‌ی انتخاب‌شده</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>تعامل</span><i class="fa-solid fa-heart"></i></div><strong>{{ number_format($metrics['engagements']) }}</strong><small>{{ $metrics['engagement_rate'] }}٪ نرخ تعامل</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>کلیک لینک</span><i class="fa-solid fa-arrow-pointer"></i></div><strong>{{ number_format($metrics['clicks']) }}</strong><small>{{ $metrics['click_rate'] }}٪ از نمایش</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>گفتگو</span><i class="fa-solid fa-comments"></i></div><strong>{{ number_format($metrics['comments'] + $metrics['messages']) }}</strong><small>{{ number_format($metrics['comments']) }} کامنت · {{ number_format($metrics['messages']) }} دایرکت</small></article><article class="mt-card mt-kpi"><div class="mt-kpi-top"><span>خرید موفق</span><i class="fa-solid fa-bag-shopping"></i></div><strong>{{ number_format($metrics['purchases']) }}</strong><small>{{ $metrics['purchase_rate'] }}٪ از کلیک</small></article></section>
    <section class="mt-grid mt-report-grid"><article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>روند عملکرد</h2><p>کلیک و بازشدن مقصد در ۱۴ روز پایانی بازه</p></div><span class="mt-badge">زمان‌محور</span></div><div class="mt-chart-box"><canvas id="marketingTrendChart" data-labels='@json($trend['labels'])' data-clicks='@json($trend['clicks'])' data-opens='@json($trend['opens'])'></canvas></div></article><article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>قیف تبدیل</h2><p>از نمایش محتوا تا خرید موفق</p></div></div><div class="mt-funnel">@foreach($funnel as $stage)<div class="mt-funnel-row"><span>{{ $stage['label'] }}</span><div><i style="width:{{ $stage['width'] }}%"></i></div><strong>{{ number_format($stage['value']) }}</strong></div>@endforeach</div></article></section>
    <section class="mt-grid mt-report-grid mt-report-grid-bottom"><article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>ترکیب کانال‌ها</h2><p>مقایسه‌ی کلیک و بازشدن مقصد</p></div></div><div class="mt-channel-report"><div class="mt-chart-donut"><canvas id="marketingChannelChart" data-labels='@json(collect($channels)->pluck('label')->all())' data-values='@json(collect($channels)->pluck('clicks')->all())'></canvas></div><div class="mt-mini-list">@foreach($channels as $channel)<div class="mt-mini-row"><span><i class="mt-mini-dot"></i>{{ $channel['label'] }}</span><strong>{{ number_format($channel['clicks']) }} کلیک</strong><small>{{ $channel['success_rate'] }}٪ موفق</small></div>@endforeach</div></div></article><article class="mt-card mt-card-pad"><div class="mt-section-head"><div><h2>عملکرد سناریوها</h2><p>برای سناریوهای ثبت‌شده در ماژول جدید</p></div><a class="mt-btn" href="{{ route('admin.marketing-technology.scenarios') }}">مدیریت سناریو</a></div>@if($topScenarios->isEmpty())<div class="mt-table-empty"><i class="fa-solid fa-comments"></i><strong>هنوز سناریویی ثبت نشده است</strong></div>@else<div class="mt-table-wrap"><table class="mt-table"><thead><tr><th>سناریو</th><th>ورودی</th><th>تبدیل</th><th>نرخ</th></tr></thead><tbody>@foreach($topScenarios as $scenario)<tr><td><strong>{{ $scenario['name'] }}</strong><small>{{ $scenario['status'] }}</small></td><td>{{ number_format($scenario['received']) }}</td><td>{{ number_format($scenario['converted']) }}</td><td><span class="mt-badge">{{ $scenario['conversion_rate'] }}٪</span></td></tr>@endforeach</tbody></table></div>@endif</article></section>
    <section class="mt-card mt-card-pad mt-table-card"><div class="mt-section-head"><div><h2>آخرین محتواها</h2><p>محتواهای جدید ماژول تکنولوژی مارکتینگ</p></div><a class="mt-btn" href="{{ route('admin.marketing-technology.content-calendar') }}">تقویم محتوا</a></div>@if($topContents->isEmpty())<div class="mt-table-empty"><i class="fa-solid fa-photo-film"></i><strong>هنوز محتوایی ثبت نشده است</strong></div>@else<div class="mt-table-wrap"><table class="mt-table"><thead><tr><th>عنوان</th><th>کانال</th><th>کمپین</th><th>وضعیت</th><th>انتشار</th></tr></thead><tbody>@foreach($topContents as $content)<tr><td><strong>{{ $content['title'] }}</strong></td><td>{{ $content['channel'] }}</td><td>{{ $content['campaign'] }}</td><td><span class="mt-badge">{{ $content['status'] }}</span></td><td>{{ $content['published_at'] ?? '—' }}</td></tr>@endforeach</tbody></table></div>@endif</section>
  </div>
</main>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>
(function(){if(typeof Chart==='undefined')return;const v=n=>getComputedStyle(document.documentElement).getPropertyValue(n).trim();const line=document.getElementById('marketingTrendChart');if(line)new Chart(line,{type:'line',data:{labels:JSON.parse(line.dataset.labels),datasets:[{label:'کلیک',data:JSON.parse(line.dataset.clicks),borderColor:v('--primary'),backgroundColor:v('--primary-l'),fill:true,tension:.4,pointRadius:2,borderWidth:2},{label:'بازشدن مقصد',data:JSON.parse(line.dataset.opens),borderColor:v('--success'),backgroundColor:v('--success-l'),fill:false,tension:.4,pointRadius:2,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,interaction:{intersect:false,mode:'index'},plugins:{legend:{position:'bottom',rtl:true,labels:{color:v('--text-soft'),usePointStyle:true,boxWidth:7,font:{family:'YekanBakh',size:10}}},tooltip:{rtl:true,bodyFont:{family:'YekanBakh'}}},scales:{x:{grid:{display:false},ticks:{color:v('--text-soft'),font:{family:'YekanBakh',size:9}}},y:{beginAtZero:true,grid:{color:v('--divider')},ticks:{color:v('--text-soft'),precision:0,font:{family:'YekanBakh',size:9}}}}}});const donut=document.getElementById('marketingChannelChart');if(donut)new Chart(donut,{type:'doughnut',data:{labels:JSON.parse(donut.dataset.labels),datasets:[{data:JSON.parse(donut.dataset.values),backgroundColor:[v('--primary'),v('--success'),v('--warning'),v('--info')],borderColor:v('--card-bg'),borderWidth:4,hoverOffset:4}]},options:{responsive:true,maintainAspectRatio:false,cutout:'70%',plugins:{legend:{display:false},tooltip:{rtl:true,bodyFont:{family:'YekanBakh'}}}}});})();
</script>
@endsection
