@extends('layouts.admin')
@section('title', 'کمپین‌های تلگرام — وطن استودیو')
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0"><div>@include('admin.partials.header')</div><div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px] max-[480px]:p-[14px]" id="content" dir="rtl">
  @if(session('success'))<div class="tg-alert">{{ session('success') }}</div>@endif
  <header class="tg-head"><div><p>ارتباط کنترل‌شده</p><h1>کمپین‌های تلگرام</h1><span>کمپین، سگمنت و فهرست گیرندگان را آماده کن؛ ارسال عمومی تا فعال‌سازی صریح شما خاموش می‌ماند.</span></div><span class="badge-pro badge-warning">ارسال عمومی خاموش</span></header>
  <div class="content-card tg-form"><h2>ساخت پیش‌نویس کمپین</h2><form method="POST" action="{{ route('admin.telegram.campaigns.store') }}">@csrf<div class="tg-form-grid"><input class="input-pro" name="name" placeholder="نام کمپین" required><input class="input-pro" name="media_type" placeholder="نوع رسانه اختیاری"><textarea class="input-pro" name="body" placeholder="متن پیام"></textarea><textarea class="input-pro" name="segment_definition" placeholder='تعریف سگمنت به صورت JSON، مثال: {"linked":true,"active_days":7,"source":"channel"}'>{"linked":true}</textarea><textarea class="input-pro" name="buttons" placeholder='دکمه‌ها به صورت JSON، مثال: [{"text":"مشاهده","url":"https://..."}]'></textarea><input class="input-pro" name="media_file_id" placeholder="شناسه فایل رسانه در تلگرام"></div><button class="btn-pro btn-pro-primary" type="submit">ذخیره پیش‌نویس</button></form></div>
  <div class="content-card tg-table-wrap"><div class="tg-table-scroll"><table class="table-pro"><thead><tr><th>کمپین</th><th>وضعیت</th><th>گیرندگان آماده</th><th>ارسال موفق</th><th>خطا</th><th>زمان</th><th></th></tr></thead><tbody>@forelse($campaigns as $campaign)<tr><td><strong>{{ $campaign->name }}</strong><small class="tg-muted">{{ $campaign->admin?->name ?: 'سیستم' }}</small></td><td><span class="badge-pro badge-warning">{{ $campaign->status === 'draft' ? 'پیش‌نویس' : $campaign->status }}</span></td><td>{{ number_format($campaign->recipient_count) }}</td><td>{{ number_format($campaign->sent_count) }}</td><td>{{ number_format($campaign->failed_count) }}</td><td>{{ $campaign->created_at?->format('Y/m/d H:i') }}</td><td>@if($campaign->status === 'draft')<form method="POST" action="{{ route('admin.telegram.campaigns.prepare', $campaign) }}">@csrf<button class="btn-pro btn-pro-ghost btn-mini" type="submit">آماده‌سازی گیرندگان</button></form>@else<span class="tg-muted">—</span>@endif</td></tr>@empty<tr><td colspan="7"><div class="empty-state">هنوز کمپینی ثبت نشده است.</div></td></tr>@endforelse</tbody></table></div><div class="pagination-bar">{{ $campaigns->links() }}</div></div>
</div></main>
<style>
.tg-alert{margin-bottom:16px;padding:12px 14px;border:1px solid var(--success-m);border-radius:12px;background:var(--success-l);color:var(--success);font-size:12px;font-weight:700}.tg-head{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:22px}.tg-head p{margin:0 0 5px;color:var(--primary);font-size:11px;font-weight:800}.tg-head h1{margin:0;color:var(--text-h);font-size:23px;font-weight:900}.tg-head span{display:block;margin-top:7px;color:var(--text-soft);font-size:12px}.tg-form{padding:19px;margin-bottom:16px}.tg-form h2{margin:0 0 14px;color:var(--text-h);font-size:14px}.tg-form form{display:grid;gap:10px}.tg-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tg-form textarea{min-height:86px;resize:vertical}.tg-form .btn-pro{justify-self:start}.tg-table-wrap{padding:0;overflow:hidden}.tg-table-scroll{overflow-x:auto}.tg-table-wrap table{min-width:900px}.tg-muted{display:block;margin-top:3px;color:var(--text-soft);font-size:10px}.btn-mini{height:32px;padding:0 10px;font-size:10px}.pagination-bar{padding:15px;border-top:1px solid var(--border)}@media(max-width:600px){.tg-head{align-items:start;flex-direction:column}.tg-form-grid{grid-template-columns:1fr}}
</style>
@endsection
