@extends('layouts.admin')
@section('title', 'محتوای بات تلگرام — وطن استودیو')
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0"><div>@include('admin.partials.header')</div><div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px] max-[480px]:p-[14px]" id="content" dir="rtl">
  @if(session('success'))<div class="tg-alert">{{ session('success') }}</div>@endif
  <header class="tg-head"><div><p>مدیریت تجربه‌ی کاربر</p><h1>متن و دکمه‌های بات</h1><span>متن، رسانه و آرایش دکمه‌های پاسخ بات را از اینجا کنترل کن.</span></div></header>
  <div class="content-card tg-form tg-create"><h2>افزودن محتوای جدید</h2><form method="POST" action="{{ route('admin.telegram.content.store') }}">@csrf<div class="tg-form-grid"><input class="input-pro" name="content_key" placeholder="کلید انگلیسی مثل welcome_extra" required><input class="input-pro" name="title" placeholder="عنوان مدیریتی"><textarea class="input-pro" name="body" placeholder="متن پیام"></textarea><textarea class="input-pro" name="buttons" placeholder='دکمه‌ها به صورت JSON، مثال: [{"text":"شروع","callback_data":"register"}]'></textarea><input class="input-pro" name="media_type" placeholder="نوع رسانه: photo / video / animation"><input class="input-pro" name="media_file_id" placeholder="شناسه فایل تلگرام"></div><button class="btn-pro btn-pro-primary" type="submit">افزودن محتوا</button></form></div>
  <div class="tg-content-list">@forelse($contents as $content)<form class="content-card tg-form" method="POST" action="{{ route('admin.telegram.content.update', $content) }}">@csrf @method('PUT')<div class="tg-content-head"><div><code>{{ $content->content_key }}</code><h2>{{ $content->title ?: 'بدون عنوان' }}</h2></div><label class="tg-check"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($content->is_active)> فعال</label></div><input class="input-pro" name="title" value="{{ $content->title }}" placeholder="عنوان مدیریتی"><textarea class="input-pro" name="body" placeholder="متن پیام">{{ $content->body }}</textarea><textarea class="input-pro" name="buttons" placeholder="JSON دکمه‌ها">{{ $content->buttons ? json_encode($content->buttons, JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT) : '' }}</textarea><div class="tg-form-grid"><input class="input-pro" name="media_type" value="{{ $content->media_type }}" placeholder="نوع رسانه"><input class="input-pro" name="media_file_id" value="{{ $content->media_file_id }}" placeholder="شناسه فایل تلگرام"></div><div class="flex items-center gap-2 flex-wrap"><button class="btn-pro btn-pro-ghost" type="submit">ذخیره تغییرات</button></div></form><form class="tg-delete-form" method="POST" action="{{ route('admin.telegram.content.destroy', $content) }}" onsubmit="return confirm('این محتوای بات حذف شود؟')">@csrf @method('DELETE')<button class="btn-pro btn-pro-danger" type="submit">حذف محتوا</button></form>@empty<div class="content-card empty-state">هنوز محتوای سفارشی ثبت نشده؛ بات از متن‌های پیش‌فرض امن استفاده می‌کند.</div>@endforelse</div>
</div></main>
<style>
.tg-alert{margin-bottom:16px;padding:12px 14px;border:1px solid var(--success-m);border-radius:12px;background:var(--success-l);color:var(--success);font-size:12px;font-weight:700}.tg-head{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:22px}.tg-head p{margin:0 0 5px;color:var(--primary);font-size:11px;font-weight:800}.tg-head h1{margin:0;color:var(--text-h);font-size:23px;font-weight:900}.tg-head span{display:block;margin-top:7px;color:var(--text-soft);font-size:12px}.tg-form{padding:19px;margin-bottom:16px}.tg-form h2{margin:0 0 14px;color:var(--text-h);font-size:14px}.tg-form form,.tg-content-list{display:grid;gap:10px}.tg-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tg-form textarea{min-height:92px;resize:vertical}.tg-form .btn-pro{justify-self:start}.tg-content-head{display:flex;align-items:start;justify-content:space-between;gap:10px;margin-bottom:5px}.tg-content-head code{color:var(--primary);font-size:11px;direction:ltr}.tg-content-head h2{margin:5px 0 0}.tg-check{display:flex;align-items:center;gap:7px;color:var(--text-main);font-size:11px}@media(max-width:600px){.tg-form-grid{grid-template-columns:1fr}.tg-head{align-items:start;flex-direction:column}}
</style>
@endsection
