@extends('layouts.admin')
@section('title', 'جزئیات کاربر تلگرام — وطن استودیو')
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0"><div>@include('admin.partials.header')</div><div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px] max-[480px]:p-[14px]" id="content" dir="rtl">
  @if(session('success'))<div class="tg-alert">{{ session('success') }}</div>@endif
  <a class="tg-back" href="{{ route('admin.telegram.users') }}"><i class="fa-solid fa-arrow-right"></i> بازگشت به کاربران</a>
  <header class="tg-profile-head"><div class="tg-profile-avatar">{{ mb_substr($telegramUser->first_name ?: 'ت', 0, 1) }}</div><div><p>پرونده‌ی کاربر تلگرام</p><h1>{{ trim($telegramUser->first_name.' '.$telegramUser->last_name) ?: 'کاربر تلگرام' }}</h1><span>{{ $telegramUser->username ? '@'.$telegramUser->username : 'بدون نام کاربری' }} · {{ $telegramUser->telegram_id }}</span></div><div class="tg-profile-status">@if($telegramUser->is_blocked)<span class="badge-pro badge-danger">خارج‌شده از ارسال</span>@else<span class="badge-pro badge-success">فعال</span>@endif</div></header>
  <section class="tg-detail-grid"><form class="content-card tg-form" method="POST" action="{{ route('admin.telegram.users.update', $telegramUser) }}">@csrf @method('PATCH')<h2>اطلاعات بات</h2><label>نام<input class="input-pro" name="first_name" value="{{ $telegramUser->first_name }}"></label><label>نام خانوادگی<input class="input-pro" name="last_name" value="{{ $telegramUser->last_name }}"></label><label>نام کاربری<input class="input-pro" name="username" value="{{ $telegramUser->username }}"></label><label class="tg-check"><input type="hidden" name="is_blocked" value="0"><input type="checkbox" name="is_blocked" value="1" @checked($telegramUser->is_blocked)> خارج‌کردن از ارسال‌های بات</label><button class="btn-pro btn-pro-primary" type="submit">ذخیره اطلاعات</button></form>
    <div class="content-card tg-form"><h2>حساب مشترک سایت</h2>@if($telegramUser->user)<div class="tg-linked"><strong>{{ trim($telegramUser->user->name.' '.$telegramUser->user->last_name) }}</strong><span>{{ $telegramUser->user->phone }}</span><b>{{ number_format($telegramUser->user->tokens) }} اعتبار</b></div><hr><h2>تغییر اعتبار</h2><form method="POST" action="{{ route('admin.telegram.users.credit', $telegramUser) }}">@csrf<select class="input-pro" name="action"><option value="add">افزودن</option><option value="deduct">کسر</option><option value="set">تنظیم موجودی</option></select><input class="input-pro" type="number" name="amount" min="0" max="1000000" placeholder="مقدار" required><input class="input-pro" name="note" placeholder="یادداشت اختیاری"><button class="btn-pro btn-pro-ghost" type="submit">ثبت تغییر اعتبار</button></form>@else<div class="empty-state">این کاربر هنوز به حساب سایت متصل نشده است.</div>@endif</div>
  </section>
  <section class="content-card tg-history"><div class="tg-card-head"><div><h2>کلیک‌های محصول</h2><p>آخرین انتخاب‌های ثبت‌شده برای این کاربر</p></div></div><div class="tg-table-scroll"><table class="table-pro"><thead><tr><th>محصول</th><th>منبع</th><th>زمان</th><th>وضعیت ساخت</th></tr></thead><tbody>@forelse($clicks as $click)<tr><td>{{ $click->product?->name_fa ?: $click->product?->name_en ?: 'محصول حذف‌شده' }}</td><td>{{ $click->source ?: 'نامشخص' }}</td><td>{{ $click->clicked_at?->format('Y/m/d H:i') }}</td><td>@if($click->opened_at)<span class="badge-pro badge-success">باز شده</span>@else<span class="badge-pro badge-neutral">فقط کلیک</span>@endif</td></tr>@empty<tr><td colspan="4"><div class="empty-state">هنوز کلیکی ثبت نشده است.</div></td></tr>@endforelse</tbody></table></div>{{ $clicks->links() }}</section>
  <form method="POST" action="{{ route('admin.telegram.users.archive', $telegramUser) }}" class="tg-archive">@csrf @method('PATCH')<button class="btn-pro btn-pro-danger" type="submit"><i class="fa-solid fa-box-archive"></i> خروج امن کاربر از بات</button><span>سوابق آماری حذف نمی‌شود.</span></form>
</div></main>
<style>
.tg-alert{margin-bottom:16px;padding:12px 14px;border:1px solid var(--success-m);border-radius:12px;background:var(--success-l);color:var(--success);font-size:12px;font-weight:700}.tg-back{display:inline-flex;gap:7px;margin-bottom:18px;color:var(--primary);font-size:11px;font-weight:800;text-decoration:none}.tg-profile-head{display:flex;align-items:center;gap:14px;margin-bottom:18px}.tg-profile-avatar{display:grid;width:58px;height:58px;place-items:center;border-radius:18px;background:var(--primary-l);color:var(--primary);font-size:24px;font-weight:900}.tg-profile-head p{margin:0 0 4px;color:var(--primary);font-size:10px}.tg-profile-head h1{margin:0;color:var(--text-h);font-size:21px}.tg-profile-head span{display:block;margin-top:4px;color:var(--text-soft);font-size:10px;direction:ltr;text-align:right}.tg-profile-status{margin-right:auto}.tg-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:16px}.tg-form{padding:19px}.tg-form h2,.tg-history h2{margin:0 0 14px;color:var(--text-h);font-size:14px}.tg-form label{display:block;margin-bottom:12px;color:var(--text-soft);font-size:11px}.tg-form label .input-pro{display:block;width:100%;margin-top:6px}.tg-check{display:flex!important;align-items:center;gap:8px;color:var(--text-main)!important}.tg-linked{display:grid;gap:7px;padding:14px;border-radius:12px;background:var(--page-bg)}.tg-linked strong{color:var(--text-h);font-size:13px}.tg-linked span{color:var(--text-soft);font-size:11px}.tg-linked b{color:var(--primary);font-size:16px}.tg-form hr{margin:18px 0;border:0;border-top:1px solid var(--border)}.tg-form form{display:grid;gap:9px}.tg-history{padding:18px;overflow:hidden}.tg-history>.table-pro{min-width:650px}.tg-history nav{margin-top:14px}.tg-archive{display:flex;align-items:center;gap:12px}.tg-archive span{color:var(--text-soft);font-size:10px}@media(max-width:760px){.tg-detail-grid{grid-template-columns:1fr}}@media(max-width:520px){.tg-profile-head{align-items:start;flex-wrap:wrap}.tg-profile-status{margin-right:0;width:100%}.tg-archive{align-items:start;flex-direction:column}}
</style>
@endsection
