@extends('layouts.admin')
@section('title', 'کاربران تلگرام — وطن استودیو')
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0"><div>@include('admin.partials.header')</div><div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px] max-[480px]:p-[14px]" id="content" dir="rtl">
  @if(session('success'))<div class="tg-alert">{{ session('success') }}</div>@endif
  <header class="tg-head"><div><p>بات تلگرام و CRM</p><h1>کاربران تلگرام</h1><span>جست‌وجو، فیلتر و بررسی مسیر ورود هر کاربر.</span></div><a class="btn-pro btn-pro-ghost" href="{{ route('admin.telegram.index') }}"><i class="fa-solid fa-chart-line"></i> داشبورد</a></header>
  <form class="content-card tg-filters" method="GET"><input class="input-pro" name="q" value="{{ request('q') }}" placeholder="نام، نام کاربری یا شناسه تلگرام"><select class="input-pro" name="status"><option value="">همه وضعیت‌ها</option><option value="active" @selected(request('status') === 'active')>فعال</option><option value="blocked" @selected(request('status') === 'blocked')>خارج‌شده از ارسال</option></select><select class="input-pro" name="linked"><option value="">اتصال به سایت</option><option value="yes" @selected(request('linked') === 'yes')>متصل</option><option value="no" @selected(request('linked') === 'no')>متصل نیست</option></select><input class="input-pro" name="source" value="{{ request('source') }}" placeholder="منبع ورود"><input class="input-pro" type="number" min="1" max="3650" name="active_days" value="{{ request('active_days') }}" placeholder="فعال در چند روز اخیر"><select class="input-pro" name="used_build"><option value="">ساخت از مسیر بات</option><option value="yes" @selected(request('used_build') === 'yes')>ساخت انجام شده</option><option value="no" @selected(request('used_build') === 'no')>هنوز ساخت نشده</option></select><input class="input-pro" type="number" min="0" max="1000000" name="builds_min" value="{{ request('builds_min') }}" placeholder="حداقل تعداد ساخت"><input class="input-pro" type="number" min="0" max="1000000" name="builds_max" value="{{ request('builds_max') }}" placeholder="حداکثر تعداد ساخت"><input class="input-pro" type="number" min="1" max="12" name="birth_month" value="{{ request('birth_month') }}" placeholder="ماه تولد (۱ تا ۱۲)"><input class="input-pro" type="date" name="created_from" value="{{ request('created_from') }}"><input class="input-pro" type="date" name="created_to" value="{{ request('created_to') }}"><button class="btn-pro btn-pro-primary" type="submit"><i class="fa-solid fa-filter"></i> اعمال فیلتر</button></form>
  <section class="content-card tg-segments"><div class="tg-card-head"><div><h2>سگمنت‌های ذخیره‌شده</h2><p>تعریف فیلترها ذخیره می‌شود؛ داده‌ی کاربران حذف یا جابه‌جا نمی‌شود.</p></div><span class="badge-pro badge-neutral">ارسال خاموش</span></div><form class="tg-segment-form" method="POST" action="{{ route('admin.telegram.segments.store') }}">@csrf<input class="input-pro" name="name" placeholder="نام سگمنت، مثلاً کاربران هفته اخیر" required><input type="hidden" name="definition" value="{{ json_encode($segmentDefinition, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}"><button class="btn-pro btn-pro-primary" type="submit"><i class="fa-solid fa-bookmark"></i> ذخیره فیلتر فعلی</button></form><div class="tg-segment-list">@forelse($segments as $segment)<div class="tg-segment-row"><div><strong>{{ $segment->name }}</strong><small>{{ number_format($segmentCounts[$segment->id] ?? $segment->user_count) }} مخاطب · تعریف فیلتر ذخیره‌شده</small></div><form method="POST" action="{{ route('admin.telegram.segments.destroy', $segment) }}">@csrf @method('DELETE')<button class="icon-action-btn" type="submit" title="حذف سگمنت" onclick="return confirm('این سگمنت حذف شود؟')"><i class="fa-solid fa-trash"></i></button></form></div>@empty<div class="empty-state">هنوز سگمنتی ذخیره نشده است.</div>@endforelse</div></section>
  <div class="content-card tg-table-wrap"><div class="tg-table-scroll"><table class="table-pro"><thead><tr><th>کاربر</th><th>شناسه</th><th>حساب سایت</th><th>کلیک محصول</th><th>ساخت انجام‌شده</th><th>آخرین فعالیت</th><th>وضعیت</th><th></th></tr></thead><tbody>
    @forelse($users as $telegramUser)<tr><td><div class="tg-person"><span class="tg-avatar">{{ mb_substr($telegramUser->first_name ?: 'ت', 0, 1) }}</span><span><strong>{{ trim($telegramUser->first_name . ' ' . $telegramUser->last_name) ?: 'کاربر تلگرام' }}</strong><small>{{ $telegramUser->username ? '@'.$telegramUser->username : 'بدون نام کاربری' }}</small></span></div></td><td><code>{{ $telegramUser->telegram_id }}</code></td><td>@if($telegramUser->user)<span class="badge-pro badge-success">متصل</span><small class="tg-muted">{{ trim($telegramUser->user->name.' '.$telegramUser->user->last_name) }}</small>@else<span class="badge-pro badge-neutral">ناقص</span>@endif</td><td>{{ number_format($telegramUser->product_clicks_count) }}</td><td>{{ number_format($telegramUser->completed_builds_count ?? 0) }}</td><td>{{ $telegramUser->last_active_at?->format('Y/m/d H:i') }}</td><td>@if($telegramUser->is_blocked)<span class="badge-pro badge-danger">خارج‌شده</span>@else<span class="badge-pro badge-success">فعال</span>@endif</td><td><a class="icon-action-btn" href="{{ route('admin.telegram.users.show', $telegramUser) }}" title="مشاهده"><i class="fa-solid fa-arrow-left"></i></a></td></tr>@empty<tr><td colspan="8"><div class="empty-state">کاربری با این فیلتر پیدا نشد.</div></td></tr>@endforelse
  </tbody></table></div><div class="pagination-bar">{{ $users->links() }}</div></div>
</div></main>
<style>
.tg-alert{margin-bottom:16px;padding:12px 14px;border:1px solid var(--success-m);border-radius:12px;background:var(--success-l);color:var(--success);font-size:12px;font-weight:700}.tg-head{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:22px}.tg-head p{margin:0 0 5px;color:var(--primary);font-size:11px;font-weight:800}.tg-head h1{margin:0;color:var(--text-h);font-size:23px;font-weight:900}.tg-head span{display:block;margin-top:7px;color:var(--text-soft);font-size:12px}.tg-filters{display:grid;grid-template-columns:minmax(180px,1.6fr) repeat(3,minmax(130px,1fr)) auto;gap:10px;margin-bottom:16px;padding:15px}.tg-segments{padding:18px;margin-bottom:16px}.tg-segment-form{display:grid;grid-template-columns:minmax(180px,1fr) auto;gap:10px;margin-bottom:14px}.tg-segment-list{display:grid;gap:8px}.tg-segment-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 12px;border:1px solid var(--border);border-radius:10px;background:var(--input-bg)}.tg-segment-row strong,.tg-segment-row small{display:block}.tg-segment-row small{margin-top:4px;color:var(--text-soft);font-size:10px}.tg-table-wrap{padding:0;overflow:hidden}.tg-table-scroll{overflow-x:auto}.tg-table-wrap table{min-width:880px}.tg-person{display:flex;align-items:center;gap:9px;min-width:180px}.tg-person strong,.tg-person small{display:block}.tg-person small,.tg-muted{display:block;margin-top:3px;color:var(--text-soft);font-size:10px}.tg-muted{white-space:nowrap}.pagination-bar{padding:15px;border-top:1px solid var(--border)}.pagination-bar nav{display:flex;justify-content:center}.pagination-bar svg{width:18px}.pagination-bar a,.pagination-bar span{color:var(--text-soft)}@media(max-width:900px){.tg-filters{grid-template-columns:1fr 1fr}.tg-filters input:first-child{grid-column:1/-1}.tg-segment-form{grid-template-columns:1fr}}@media(max-width:520px){.tg-head{align-items:start;flex-direction:column}.tg-filters{grid-template-columns:1fr}.tg-filters input:first-child{grid-column:auto}}
</style>
@endsection
