@extends('layouts.admin')
@section('title', 'مدیریت تیکت — وطن استودیو')
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0" dir="rtl">
  @include('admin.partials.header')
  <div class="admin-content flex-1 overflow-y-auto p-6 max-[768px]:p-[18px]" id="content">
    <div class="support-admin-head"><div><a href="{{ route('admin.support.index') }}" class="support-admin-back"><i class="fa-solid fa-arrow-right"></i> همه تیکت‌ها</a><h1>{{ $ticket->subject }}</h1><p>{{ $ticket->ticket_number }} · {{ $ticket->user?->name ?: 'کاربر حذف‌شده' }} · {{ $ticket->user?->phone ?: $ticket->user?->email }}</p></div></div>
    @if(session('success'))<div class="support-admin-success">{{ session('success') }}</div>@endif
    <div class="support-admin-detail"><section class="support-admin-thread">@foreach($ticket->messages as $message)<article class="support-admin-message support-admin-message--{{ $message->sender_type }}"><small>{{ $message->sender_type === 'admin' ? 'پشتیبانی وطن' : ($ticket->user?->name ?: 'کاربر') }} · {{ $message->created_at?->format('Y/m/d H:i') }}</small><p>{{ $message->body }}</p></article>@endforeach<form action="{{ route('admin.support.reply', $ticket) }}" method="POST" class="support-admin-reply">@csrf<textarea name="body" rows="5" placeholder="پاسخ خود را برای کاربر بنویسید..." required></textarea><button type="submit">ارسال پاسخ <i class="fa-solid fa-paper-plane"></i></button></form></section><aside class="support-admin-sidebar"><h2>مدیریت درخواست</h2><form action="{{ route('admin.support.update', $ticket) }}" method="POST" class="support-admin-management">@csrf @method('PATCH')<label>وضعیت<select name="status"><option value="open" @selected($ticket->status==='open')>باز</option><option value="pending" @selected($ticket->status==='pending')>در انتظار پاسخ</option><option value="answered" @selected($ticket->status==='answered')>پاسخ داده‌شده</option><option value="closed" @selected($ticket->status==='closed')>بسته‌شده</option></select></label><label>اولویت<select name="priority"><option value="low" @selected($ticket->priority==='low')>کم</option><option value="normal" @selected($ticket->priority==='normal')>عادی</option><option value="high" @selected($ticket->priority==='high')>زیاد</option><option value="urgent" @selected($ticket->priority==='urgent')>فوری</option></select></label><label>مسئول رسیدگی<select name="assigned_admin_id"><option value="">بدون مسئول</option>@foreach($admins as $admin)<option value="{{ $admin->id }}" @selected($ticket->assigned_admin_id===$admin->id)>{{ $admin->name }}</option>@endforeach</select></label><button type="submit">ذخیره تغییرات</button></form><div class="support-admin-contact"><span>کانال</span><b>{{ $ticket->channel === 'site' ? 'سایت' : $ticket->channel }}</b><span>دسته‌بندی</span><b>{{ $ticket->categoryLabel() }}</b></div></aside></div>
  </div>
</main>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('admin/css/support.css') }}?v={{ filemtime(public_path('admin/css/support.css')) }}">@endpush
