@extends('layouts.admin')
@section('title', 'صفحه بساز — مدیریت ساخت‌های هوش مصنوعی')
@push('styles')
<link rel="stylesheet" href="{{ asset('admin/css/create-studio.css') }}?v={{ filemtime(public_path('admin/css/create-studio.css')) }}">
@endpush
@php
  $statusLabels = ['completed' => 'تکمیل‌شده', 'success' => 'موفق', 'processing' => 'در حال پردازش', 'queued' => 'در صف', 'submitting' => 'در حال ارسال', 'failed' => 'ناموفق', 'canceled' => 'لغوشده'];
  $statusClass = fn ($status) => in_array($status, ['completed', 'success'], true) ? 'success' : (in_array($status, ['failed', 'canceled'], true) ? 'danger' : 'warning');
  $providerLabels = ['openrouter' => 'OpenRouter', 'fal' => 'Fal.ai', 'replicate' => 'Replicate'];
@endphp
@section('content')
<main class="mr-[294px] flex-1 min-h-screen flex flex-col min-w-0 max-[900px]:mr-0">
  @include('admin.partials.header')
  <div class="admin-content flex-1 overflow-y-auto" id="content">
    <div class="create-studio-admin" dir="rtl">
      <div class="create-studio-admin-head"><div><h1>صفحه بساز</h1><div class="create-studio-admin-subtitle">مدیریت ساخت‌های عکس و ویدیو، اعتبار مصرفی، هزینه‌ی سرویس و سود هر خروجی</div></div><div class="create-studio-admin-actions"><a class="create-studio-admin-btn" href="{{ route('app.create.studio') }}" target="_blank"><i class="fa-solid fa-arrow-up-right-from-square"></i> مشاهده استودیو</a><a class="create-studio-admin-btn primary" href="#cost-rules"><i class="fa-solid fa-sliders"></i> تنظیم سود</a></div></div>
      @if(session('success'))<div class="create-studio-admin-alert">{{ session('success') }}</div>@endif
      @if(isset($errors) && $errors->any())<div class="create-studio-admin-alert create-studio-admin-alert-danger">{{ $errors->first() }}</div>@endif
      <nav class="create-studio-admin-tabs"><a class="{{ $tab === 'overview' ? 'active' : '' }}" href="{{ route('admin.create-studio.index', ['tab' => 'overview']) }}">نمای کلی</a><a class="{{ $tab === 'generations' ? 'active' : '' }}" href="{{ route('admin.create-studio.index', ['tab' => 'generations']) }}#generations">لیست ساخته‌ها</a><a class="{{ $tab === 'costs' ? 'active' : '' }}" href="{{ route('admin.create-studio.index', ['tab' => 'costs']) }}#cost-rules">مدیریت هزینه و سود</a><a class="{{ $tab === 'credits' ? 'active' : '' }}" href="{{ route('admin.create-studio.index', ['tab' => 'credits']) }}#credit-architecture">معماری اعتبار</a></nav>
      <section class="create-studio-admin-stats"><article class="create-studio-admin-stat"><span>کل درخواست‌های ساخت</span><strong>{{ number_format($stats['orders']) }}</strong><small>سفارش واقعی از اپ</small></article><article class="create-studio-admin-stat"><span>ساخت‌های موفق</span><strong>{{ number_format($stats['completed']) }}</strong><small>{{ number_format($stats['success_rate'], 1) }}٪ نرخ موفقیت</small></article><article class="create-studio-admin-stat"><span>خروجی عکس</span><strong>{{ number_format($stats['images']) }}</strong><small>ذخیره‌شده در گالری</small></article><article class="create-studio-admin-stat"><span>خروجی ویدیو</span><strong>{{ number_format($stats['videos']) }}</strong><small>ثبت‌شده در صف و گالری</small></article><article class="create-studio-admin-stat"><span>اعتبار مصرف‌شده</span><strong>{{ number_format($stats['credits']) }}</strong><small>بر اساس سفارش‌های اپ</small></article><article class="create-studio-admin-stat"><span>هزینه سرویس</span><strong>${{ number_format($stats['usd'], 4) }}</strong><small>هزینه‌ی پروایدر</small></article></section>
      <div class="create-studio-admin-grid">
        <section class="create-studio-admin-panel" id="generations"><div class="create-studio-admin-panel-head"><div><h2>لیست ساخته‌ها</h2><div class="create-studio-admin-panel-caption">کدام کاربر چه چیزی را با کدام مدل و چه هزینه‌ای ساخته است</div></div><span class="create-studio-admin-badge">{{ number_format($recentGenerations->count()) }} مورد</span></div><div class="create-studio-admin-table-wrap"><table class="create-studio-admin-table"><thead><tr><th>کاربر</th><th>نوع و محصول</th><th>مدل / سرویس</th><th>وضعیت</th><th>اعتبار</th><th>هزینه</th><th>زمان</th></tr></thead><tbody>@forelse($recentGenerations as $generation)<tr><td><strong>{{ $generation['user'] }}</strong><small>#{{ $generation['id'] }}</small></td><td><span class="create-studio-admin-badge">{{ $generation['media_label'] }}</span>@if($generation['is_sample'] ?? false)<span class="create-studio-admin-badge sample">نمونه</span>@endif<small>{{ $generation['product'] }}</small></td><td><strong>{{ $generation['model'] }}</strong><small>{{ $providerLabels[strtolower($generation['provider'])] ?? strtoupper($generation['provider']) }} · {{ ($generation['attempts'] ?? 1) > 1 ? 'مدل جایگزین فعال' : (($generation['is_sample'] ?? false) ? 'نمونه‌ی مدل اصلی' : 'مدل اصلی') }}</small></td><td><span class="create-studio-admin-badge {{ $statusClass($generation['status']) }}">{{ $statusLabels[$generation['status']] ?? $generation['status'] }}</span></td><td>{{ number_format($generation['credits']) }}</td><td>${{ number_format($generation['usd'], 6) }}</td><td>{{ optional($generation['created_at'])->format('Y/m/d H:i') }}</td></tr>@empty<tr><td colspan="7">هنوز ساختی در سیستم ثبت نشده است.</td></tr>@endforelse</tbody></table></div></section>
        <section class="create-studio-admin-panel" id="credit-architecture"><div class="create-studio-admin-panel-head"><div><h2>معماری اعتبار</h2><div class="create-studio-admin-panel-caption">محاسبه‌ی اعتبار از قیمت واقعی مدل تا رزرو، تسویه یا بازگشت اعتبار</div></div></div><div class="create-studio-admin-architecture"><article><i class="fa-solid fa-database"></i><h3>۱. قیمت مدل</h3><p>قیمت رسمی مدل و پروایدر، همراه با کیفیت، نسبت، مدت و تعداد خروجی خوانده می‌شود.</p></article><article><i class="fa-solid fa-percent"></i><h3>۲. سود وطن</h3><p>درصد سود عکس یا ویدیو روی هزینه‌ی واقعی اعمال و قیمت فروش به تومان محاسبه می‌شود.</p></article><article><i class="fa-solid fa-wallet"></i><h3>۳. رزرو و تسویه</h3><p>اعتبار قبل از ارسال درخواست رزرو و پس از موفقیت تسویه می‌شود؛ در خطا بازمی‌گردد.</p></article></div></section>
      </div>
      <section class="create-studio-admin-panel" id="cost-rules"><div class="create-studio-admin-panel-head"><div><h2>قیمت‌گذاری خودکار هر ساخت</h2><div class="create-studio-admin-panel-caption">هزینه‌ی پایه از کاتالوگ مدل و پروایدر می‌آید؛ شما فقط درصد سود را برای عکس و ویدیو مشخص می‌کنید.</div></div><span class="create-studio-admin-badge">هر اعتبار = ۱٬۰۰۰ تومان</span></div>
        <form class="create-studio-admin-form" method="POST" action="{{ route('admin.create-studio.pricing-settings.update') }}">@csrf @method('PUT')
          <div class="create-studio-admin-field"><label for="image_profit_percent">سود ساخت عکس، درصد</label><input id="image_profit_percent" type="number" step="0.01" min="0" max="1000" name="image_profit_percent" value="{{ old('image_profit_percent', $pricingSettings->image_profit_percent) }}" required><small>هزینه‌ی مدل × نرخ ارز × (۱ + درصد سود)</small></div>
          <div class="create-studio-admin-field"><label for="video_profit_percent">سود ساخت ویدیو، درصد</label><input id="video_profit_percent" type="number" step="0.01" min="0" max="1000" name="video_profit_percent" value="{{ old('video_profit_percent', $pricingSettings->video_profit_percent) }}" required><small>مدت و کیفیت ویدیو در قیمت مدل لحاظ می‌شود</small></div>
          <div class="create-studio-admin-field create-studio-admin-field-note"><i class="fa-solid fa-circle-info"></i><span>قیمت مدل، کیفیت و مدت از داده‌ی پروایدر خوانده می‌شود. مدل بدون قیمت معتبر در زمان ساخت متوقف می‌شود تا اعتبار اشتباه از کاربر کم نشود.</span></div>
          <div class="create-studio-admin-form-actions"><button class="create-studio-admin-btn primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> ذخیره درصد سود</button></div>
        </form>
      </section>
      <section class="create-studio-admin-panel"><div class="create-studio-admin-panel-head"><div><h2>پوشش قیمت مدل‌ها</h2><div class="create-studio-admin-panel-caption">همه‌ی مدل‌های فعال سه پروایدر در استودیو قابل مشاهده‌اند؛ مدل بدون قیمت قبل از ساخت علامت‌گذاری می‌شود.</div></div></div><div class="create-studio-admin-architecture">@foreach($providerCoverage as $provider => $coverage)<article><i class="fa-solid fa-server"></i><h3>{{ $providerLabels[$provider] ?? strtoupper($provider) }}</h3><p>{{ number_format($coverage['priced']) }} مدل قیمت‌دار · {{ number_format($coverage['missing']) }} مدل بدون قیمت · مجموع {{ number_format($coverage['total']) }}</p></article>@endforeach</div><div class="create-studio-admin-table-wrap"><table class="create-studio-admin-table"><thead><tr><th>نوع</th><th>مدل</th><th>پروایدر</th><th>هزینه پایه</th><th>منبع قیمت</th><th>وضعیت</th></tr></thead><tbody>@forelse($pricedModels as $model)<tr><td>{{ $model['media_type'] === 'video' ? 'ویدیو' : 'عکس' }}</td><td><strong>{{ $model['name'] }}</strong></td><td>{{ $providerLabels[$model['provider']] ?? strtoupper($model['provider']) }}</td><td>@if($model['price_usd'] !== null)${{ number_format($model['price_usd'], 6) }}@else—@endif</td><td>{{ $model['pricing_source'] }}</td><td><span class="create-studio-admin-badge {{ $model['cost_known'] ? 'success' : 'warning' }}">{{ $model['cost_known'] ? 'قیمت‌دار' : 'بدون قیمت' }}</span></td></tr>@empty<tr><td colspan="6">مدل فعالی ثبت نشده است.</td></tr>@endforelse</tbody></table></div></section>
    </div>
  </div>
</main>
@endsection
